### ISSUE TITLE
flutter of birds II 天使たちの翼

### ISSUE THREAD

**Issue by bigzain26** [HIllya51/LunaHook#100]
### vndb link/id

https://vndb.org/v2380

### Game resource 游戏资源

https://drive.google.com/drive/folders/1rXIqwkKIsgVBu_fAAkYiaACllqt73hsQ?usp=drive_link 

### screenshot 截图

![Screenshot (14)](https://github.com/user-attachments/assets/c058f8fb-1e36-4970-b9c1-b03aa7894792)
![Screenshot (15)](https://github.com/user-attachments/assets/2c73e5c0-8bd8-406b-8343-cfcc0a0511c2)
![Screenshot (17)](https://github.com/user-attachments/assets/c3c5efb4-0b98-4882-8b17-e0b996db8c9c)
![Screenshot (16)](https://github.com/user-attachments/assets/4bfdd9a7-b603-4c10-851a-a281555c7a5b)![Screenshot (17)](https://github.com/user-attachments/assets/8c36a8ef-bd76-412f-a3cb-404613431fd3)

**Comment by HIllya51** [comment]
dont ask me anything before update to latest version

**Comment by bigzain26** [comment]
I tried again after updating to the newest version and it still didn't work. Here are the screenshots 
![Screenshot (18)](https://github.com/user-attachments/assets/addc4dc4-b782-498b-ad3a-e70880d1bd49)
![Screenshot (19)](https://github.com/user-attachments/assets/f6ab1c49-3ce9-4ec8-b21e-e58dca1a87b8)

**Comment by bigzain26** [comment]
> I tried again after updating to the newest version and it still didn't work. Here are the screenshots ![Screenshot (18)](https://private-user-images.githubusercontent.com/176779344/352871151-addc4dc4-b782-498b-ad3a-e70880d1bd49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMDI5NzgsIm5iZiI6MTcyMjIwMjY3OCwicGF0aCI6Ii8xNzY3NzkzNDQvMzUyODcxMTUxLWFkZGM0ZGM0LWI3ODItNDk4Yi1hZDNhLWU3MDg4MGQxYmQ0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQyMTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjUwMjljZjRjNTZkNDlmYTg4ZjMxNzQ0YzAxNjEyYzAzMTkxMTNlY2FhZDc3MjM0NGE2MWM2MjYzYzVmMzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZIf-OR5IKc9Okg7dD9qO6-aRC08GTMlUNH_xNESbFP8) ![Screenshot (19)](https://private-user-images.githubusercontent.com/176779344/352871152-f6ab1c49-3ce9-4ec8-b21e-e58dca1a87b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMDI5NzgsIm5iZiI6MTcyMjIwMjY3OCwicGF0aCI6Ii8xNzY3NzkzNDQvMzUyODcxMTUyLWY2YWIxYzQ5LTNjZTktNGVjOC1iMjFlLWU1OGRjYTFhODdiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQyMTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTZhM2Q5OTFmNDkyYjU3OTFkOTA4YjM0OWRjYzJiMzUzMTk1NTVlYTQ2NmJkZjI3YWMxZTQ1ZTU0M2I0NDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9QLygDM55WJfTWJTKa7MV9s1cktIh6k2quJIsgzdZvA)



> dont ask me anything before update to latest version

I tried again after updating to the newest version, but it still didn't work. Here are the screenshots 
![Screenshot (18)](https://github.com/user-attachments/assets/44edac90-df0c-4d22-80d3-45290311c6dc)
![Screenshot (19)](https://github.com/user-attachments/assets/88e5c930-022e-4019-935d-fe997d580090)

**Comment by HIllya51** [comment]
First of all, why would you give me a program that can't run?

![屏幕截图 2024-07-29 113013](https://github.com/user-attachments/assets/dcaa60b0-006f-4a62-a7b2-a72dbcd3e295)


Secondly, support for this game is very clear.

https://github.com/HIllya51/LunaHook/commit/d5d882f7fc39cc93462a7247fed53dda470ed0e9

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/7423cd40e5f0738a78fe4bbcc2c9e7f930a00663

**Comment by HIllya51** [comment]
Very strange, someone asked me to adapt the same game two weeks ago, not sure why it doesn't work for you.

https://github.com/HIllya51/LunaHook/commit/d5d882f7fc39cc93462a7247fed53dda470ed0e9

**Comment by bigzain26** [comment]
Thanks for the help, I got it to work. I just had to search for the hook code by using the text search option and it started working.

**Comment by HIllya51** [comment]
using `EDSNHS932#-8@42650:Angel.exe` which support embed translation

**Comment by bigzain26** [comment]
just tried that one, it works as well. thanks!
