### ISSUE TITLE
elf的游戏el win10对应版无法hook

### ISSUE THREAD

**Issue by vexling201515** [HIllya51/LunaHook#101]
### vndb link/id

https://vndb.org/v2293

### Game resource 游戏资源

https://gofile.io/d/ulLQRK

### screenshot 截图

![屏幕截图 2024-07-29 000941](https://github.com/user-attachments/assets/55917d7c-ba6a-4126-a9b8-9178310c3498)
![QQ截图20240729001035](https://github.com/user-attachments/assets/8edbd62e-335f-4e1d-b9ac-8eda7b7778ff)

**Comment by vexling201515** [comment]
按alt+enter全屏切换成窗口

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/ec050e22744ff0772fd691be8e5e521c4d603626
