### ISSUE TITLE
Select Oblige: Characters with reading (ruby/furigana) not hooked with Artemis64

### ISSUE THREAD

**Issue by ripdog** [HIllya51/LunaHook#102]
### vndb link/id

https://vndb.org/v47175

### Game resource 游戏资源

https://mega.nz/folder/Nc0yzRgY#e8IayVgwcQoP5VM-5TCGdg

### screenshot 截图

![image](https://github.com/user-attachments/assets/5c223bab-28b3-4627-8e19-22f92fe468f2)

Most text is extracted correctly, but characters with readings above them are ignored. This also happens when characters have a dot above them for emphasis.

The small text should be ignored, not hooked.

Thank you very much!

**Comment by HIllya51** [comment]
Not interested in wasting time. If there are minor mistakes, fix them yourself.

**Comment by HIllya51** [comment]
![屏幕截图 2024-07-29 112221](https://github.com/user-attachments/assets/01f788e6-f85e-4202-a652-c411da803c86)
