### ISSUE TITLE
文本错乱

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#104]
### vndb link/id

https://vndb.org/v6180

### Game resource 游戏资源

https://mega.nz/file/ELlAAKrD#Po6X3nIRFCnzBTSIQwK9hvOSDFxO4GbBG9Jf-8yyKwA

### screenshot 截图

![1](https://github.com/user-attachments/assets/170de648-ef9a-42cf-a2e4-3fc5cfdb71c9)
超出一行的文本会跑到前面

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/636988b9276c0ac770b4708ed4ff96b1efb621d5
