### ISSUE TITLE
缺字

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#106]
### vndb link/id

https://vndb.org/v4053

### Game resource 游戏资源

https://zi0.cc/d/%60%E3%80%90%E5%90%88%E9%9B%86%E7%B3%BB%E5%88%97%E3%80%91/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86-4/2004%E5%B9%B46%E6%9C%88/%E4%BC%9A%E7%A4%BE%E5%90%88%E9%9B%86/%5B040604%5D%5BDISCOVERY%5D%20%E5%B0%8F%E9%9B%AA%E3%81%AE%E6%9C%B1%20%EF%BD%9E%E3%82%B3%E3%83%A6%E3%82%AD%E3%83%8E%E3%82%A2%E3%82%AB%EF%BD%9E%20(bin%2Bcue).rar?sign=HLEBiUF3s8OduaHEXlmdWAdxMnMtMNvxoii2dJzx5jE=:0

### screenshot 截图

![1](https://github.com/user-attachments/assets/cf534632-e6e4-47da-91cf-3fe0c6f2b602)

**Comment by HIllya51** [comment]
这玩意儿咋退出全屏，醉了

**Comment by qscasdasd** [comment]
> 这玩意儿咋退出全屏，醉了
窗口化工具：https://mega.nz/file/JCl1FTrZ#EH2ZNJvUdKx-nMce2dFCnvT-9CEq1QG-sfJcC-RSCz8
演示视频：https://gofile.io/d/wo3pu7
