### ISSUE TITLE
Random Crashes with ChatGPT API in LunaTranslator 5.23.3 (64-bit)

### ISSUE THREAD

**Issue by Cloudstrifeff7** [HIllya51/LunaHook#108]
### Version 程序版本

5.23.3 64 bit

### Reproduction steps 复现步骤

Bug Title:
Random Crashes with ChatGPT API in LunaTranslator 5.23.3 (64-bit)

Description:
LunaTranslator 5.23.3 (64-bit) crashes randomly when using the ChatGPT API in Large model mode. The issue appears after the initial translations are processed. Once the first crash occurs, subsequent translation attempts result in repeated crashes. The only temporary fix is to restart the PC, but the issue reappears shortly after.

Steps to Reproduce:

1. Open LunaTranslator 5.23.3 (64-bit).
2. Set the translation API to ChatGPT from Large model.
3. Perform a few translations.
4. Observe the random crash after some translations.
5. Reopen LunaTranslator and attempt to translate again.
6. Notice that the program crashes again without successfully translating.
7. Expected Behavior:
8. The program should consistently translate text using the ChatGPT API in Large model mode without crashing.

Actual Behavior:

- Initial translations are processed.
- The program crashes randomly after a few translations.
- After the first crash, the program fails to translate and crashes again.
- Restarting the PC temporarily fixes the issue, but the bug reoccurs.

Environment:

OS: Windows 11 Pro
LunaTranslator Version: 5.23.3 (64-bit)
ChatGPT API Large Model

**Comment by HIllya51** [comment]
不要在这里发。
https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=bug&projects=&template=01_bug.yaml
