### ISSUE TITLE
Doesn't load saved user hook

### ISSUE THREAD

**Issue by SnowLynnx** [HIllya51/LunaHook#11]
I insert user hook, select "Remember Hook Selection" for it, select autoattach in settings, close LunaHook and lauch it again, it autoattaches to VN and loads only default hooks, without the userhook that I added (even though the hook is saved in config file).
Mentioned above is for LunaHost32.
As for LunaHost64, if I use "Remember Hook Selection" and have the autoattach setting on, the app crashes right after the launch (if I delete saved hook from config file it launches fine again)

**Comment by HIllya51** [comment]
It is supported now.
But actually, I more suggest that you tell me the games that cannot be automatically hooked, so that I can add them to the built-in support. This will also make it more convenient for people who play the same game in the future.

**Comment by SnowLynnx** [comment]
Thanks, now it loads the hook correctly, but I still have the issue with LunaHost64 crashing on launch. Now it seems to be because of textractor plugins that I added. It launches fine if I remove them. 32 version launches fine with the same plugins. Here's the list:
![image](https://github.com/HIllya51/LunaHook/assets/167159322/1998de2b-d778-4840-88f2-71f341aa7883)

Also, would be great if it saved not just one hook, but the state of all hooks as textractor does. In textractor I usually remove the hooks that I don't need and leave only 1-2 that I need, save it, and textractor doesn't load the hooks that I removed.

**Comment by SnowLynnx** [comment]
> I more suggest that you tell me the games that cannot be automatically hooked, so that I can add them to the built-in support. 

https://vndb.org/v23466
https://vndb.org/v21857

**Comment by HIllya51** [comment]
> Thanks, now it loads the hook correctly, but I still have the issue with LunaHost64 crashing on launch. Now it seems to be because of textractor plugins that I added. It launches fine if I remove them. 32 version launches fine with the same plugins. Here's the list:

It works fine and not crash for me
<img width="1071" alt="屏幕截图 2024-04-16 145234" src="https://github.com/HIllya51/LunaHook/assets/101191390/3dd21aab-cba7-4877-97fb-9fcc259b6080">

**Comment by HIllya51** [comment]
> > I more suggest that you tell me the games that cannot be automatically hooked, so that I can add them to the built-in support.我更建议你告诉我不能自动挂钩的游戏，这样我就可以将它们添加到内置支持中。
> 
> https://vndb.org/v23466 https://vndb.org/v21857

https://github.com/HIllya51/LunaHook/commit/59bf949a129e46ce163e77dcbeb48b1d9582db7e
these two games are already build-in 2.10.1 (actually in 2.10.0 is inclued, I supported them without release a new version number)

**Comment by SnowLynnx** [comment]
> > Thanks, now it loads the hook correctly, but I still have the issue with LunaHost64 crashing on launch. Now it seems to be because of textractor plugins that I added. It launches fine if I remove them. 32 version launches fine with the same plugins. Here's the list:
> 
> It works fine and not crash for me <img alt="屏幕截图 2024-04-16 145234" width="1071" src="https://private-user-images.githubusercontent.com/101191390/322732702-3dd21aab-cba7-4877-97fb-9fcc259b6080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTEyNjUsIm5iZiI6MTcxMzI1MDk2NSwicGF0aCI6Ii8xMDExOTEzOTAvMzIyNzMyNzAyLTNkZDIxYWFiLWNiYTctNDg3Ny05N2ZiLTlmY2MyNTliNjA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNzAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjJmM2RkOWZkNTJlY2JhMzljNjY4MGMwZTBhN2JhZDY3YzQzZTZmZDQ0NjJiNDNlYTc2YzYwY2FjZDM3ZTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.97kUYfkHm8fUuRyHFvHUzMdvjSPK-dTh2hre-ksWzgc">

Maybe your settings are different? I have these:
![image](https://github.com/HIllya51/LunaHook/assets/167159322/5a5eb533-57a4-4f75-abd4-579bb7869fc1)

**Comment by HIllya51** [comment]
all same.

**Comment by SnowLynnx** [comment]
> > > I more suggest that you tell me the games that cannot be automatically hooked, so that I can add them to the built-in support.我更建议你告诉我不能自动挂钩的游戏，这样我就可以将它们添加到内置支持中。
> > 
> > 
> > https://vndb.org/v23466 https://vndb.org/v21857
> 
> [59bf949](https://github.com/HIllya51/LunaHook/commit/59bf949a129e46ce163e77dcbeb48b1d9582db7e) these two games are already build-in 2.10.1 (actually in 2.10.0 they are suppored, I supported them without release a new version number)

It inserts some hooks, but none of them contains the text from the VN

**Comment by HIllya51** [comment]
Well, it doesn’t matter. Since Host32 can be used, you can just use Host32. There is no difference between the two Hosts.

**Comment by HIllya51** [comment]
> > > > I more suggest that you tell me the games that cannot be automatically hooked, so that I can add them to the built-in support.我更建议你告诉我不能自动挂钩的游戏，这样我就可以将它们添加到内置支持中。
> > > 
> > > 
> > > https://vndb.org/v23466 https://vndb.org/v21857
> > 
> > 
> > [59bf949](https://github.com/HIllya51/LunaHook/commit/59bf949a129e46ce163e77dcbeb48b1d9582db7e) these two games are already build-in 2.10.1 (actually in 2.10.0 they are suppored, I supported them without release a new version number)
> 
> It inserts some hooks, but none of them contains the text from the VN

Maybe we are using different release, I have tested OK on official release.

**Comment by SnowLynnx** [comment]
> > > > > I more suggest that you tell me the games that cannot be automatically hooked, so that I can add them to the built-in support.我更建议你告诉我不能自动挂钩的游戏，这样我就可以将它们添加到内置支持中。
> > > > 
> > > > 
> > > > https://vndb.org/v23466 https://vndb.org/v21857
> > > 
> > > 
> > > [59bf949](https://github.com/HIllya51/LunaHook/commit/59bf949a129e46ce163e77dcbeb48b1d9582db7e) these two games are already build-in 2.10.1 (actually in 2.10.0 they are suppored, I supported them without release a new version number)
> > 
> > 
> > It inserts some hooks, but none of them contains the text from the VN
> 
> Maybe we are using different release, I have tested OK on official release.

I used v2.10.1, which seems to be the latest one

**Comment by SnowLynnx** [comment]
> Well, it doesn’t matter. Since Host32 can be used, you can just use Host32. There is no difference between the two Hosts.

As I see, LunaHook compatible with both 32x and 64x VNs, so I guess I will do just that. I remember textractor cannot hook 64x VNs from 32x version

**Comment by HIllya51** [comment]
> > > > > > I more suggest that you tell me the games that cannot be automatically hooked, so that I can add them to the built-in support.我更建议你告诉我不能自动挂钩的游戏，这样我就可以将它们添加到内置支持中。
> > > > > 
> > > > > 
> > > > > https://vndb.org/v23466 https://vndb.org/v21857
> > > > 
> > > > 
> > > > [59bf949](https://github.com/HIllya51/LunaHook/commit/59bf949a129e46ce163e77dcbeb48b1d9582db7e) these two games are already build-in 2.10.1 (actually in 2.10.0 they are suppored, I supported them without release a new version number)
> > > 
> > > 
> > > It inserts some hooks, but none of them contains the text from the VN
> > 
> > 
> > Maybe we are using different release, I have tested OK on official release.
> 
> I used v2.10.1, which seems to be the latest one

I say the release of VN. I have tested all OK of these two vn. Well, it doesn’t matter.

**Comment by HIllya51** [comment]
> > Well, it doesn’t matter. Since Host32 can be used, you can just use Host32. There is no difference between the two Hosts.
> 
> As I see, LunaHook32 compatible with both 32x and 64x VNs, so I guess I will do just that. I remember textractor cannot hook 64x VNs from 32x version

Yes, this is an another improvement over Textractor.

**Comment by SnowLynnx** [comment]
> Also, would be great if it saved not just one hook, but the state of all hooks as textractor does. In textractor I usually remove the hooks that I don't need and leave only 1-2 that I need, save it, and textractor doesn't load the hooks that I removed.

@HIllya51 what about this?

**Comment by HIllya51** [comment]
It seems to make no sense. Is there any disadvantage of keeping all of hook?

**Comment by SnowLynnx** [comment]
Sometimes VNs have hooks that constantly spam a lot of text in some threads and it seems to impact the PC performance. I usually play VNs on low spec laptop though.

**Comment by HIllya51** [comment]
Textractor seems not support auto remove hook, so I will not support too.
If you want auto remove useless hooks, you can use LunaTranslator

**Comment by HIllya51** [comment]
actually , even not remove useless hooks, it only spend a few MB extra memory.
