### ISSUE TITLE
clannad的英文版hook出来是乱码

### ISSUE THREAD

**Issue by Stillily** [HIllya51/LunaHook#113]
### vndb link/id

clannad

### Game resource 游戏资源

https://pixeldrain.com/u/73tT2w4S

### screenshot 截图

![WeChat截图_20240810233331](https://github.com/user-attachments/assets/ab19b954-d29b-44e0-b2e0-4945baa55790)

**Comment by HIllya51** [comment]
改下代码页

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/621fd866e64ef7454aab08eb1a9a37b9fe3af7c5

**Comment by Stillily** [comment]
感谢，已解决
