### ISSUE TITLE
是MARIKIN ONLINE 3这个

### ISSUE THREAD

**Issue by dsnailb** [HIllya51/LunaHook#115]
### Game resource 游戏资源

https://www.mediafire.com/file/7tnscgz4a5d3gob/TEAMALPHA.rar/file

### screenshot 截图

![屏幕截图 2024-08-11 235938](https://github.com/user-attachments/assets/cfd65b21-ad28-4331-a57f-0a41e3dbaa2b)

**Comment by dsnailb** [comment]
Lunatranslator hook不到rpgmaker做的这个游戏的文本，谢谢老大看一眼

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/406438bb427674c718faf69cb2dfc49e352e6c03
