### ISSUE TITLE
Can't Inject hook in willow soft game mamasen 

### ISSUE THREAD

**Issue by Funkylionz** [HIllya51/LunaHook#116]
### vndb link/id

https://vndb.org/v5761#main

### Game resource 游戏资源

https://mypikpak.com/s/VNjqFm7Di3b5LkEm09cX7m4zo1/VNjavMBEp_Tk44qcfKV7DO11o1?act=play

### screenshot 截图

![Screenshot (2)](https://github.com/user-attachments/assets/5d84d0be-ea96-42cd-b1d0-ce12ca2d0ace)
![Screenshot (3)](https://github.com/user-attachments/assets/20dea3cf-061c-4751-ac4e-4ed72438203b)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/d31698c5d1b5a5d52f664c232d968e5ea33357f4

**Comment by Funkylionz** [comment]
Thanks you're a king
