### ISSUE TITLE
Seijun na Karada wa, Aitsu no Ude no Naka de Otoko o Shitteiku -Kanojo no Shiawasesou na Sugata o, Yubi o Kuwaete Miteirushika Nai Monogatari-

### ISSUE THREAD

**Issue by Solanastar** [HIllya51/LunaHook#118]
### vndb link/id

https://vndb.org/v5688

### Game resource 游戏资源

https://drive.google.com/file/d/1roWuz1DLlBJ9U0pCleFNhBdjD6uKMr2_/view?usp=drive_link

### screenshot 截图

![image](https://github.com/user-attachments/assets/ee000039-d45d-4603-a117-fe337b2990dc)

**Comment by HIllya51** [comment]
link is invalid
