### ISSUE TITLE
Invalid dll - x86 and x64 Textractor dll's don't work.

### ISSUE THREAD

**Issue by Tor-Saxberg** [HIllya51/LunaHook#119]
### Version 程序版本

v3.9.0, english version

### Related screenshot (optional) 相关截图（可选）

I just get a pop-up saying invalid dll.

### Reproduction steps 复现步骤

copy xdll from Textractor directory (e.g "DeepL Translate.xdll")
paste it into LunaHook directory.
download  plugin64 into the LunaHook directory. 
run LunaHost64.exe
try to add any Textractor plugin.

**Comment by HIllya51** [comment]
Don't ask me questions about textractor's plugin, I'm not interested in it.

**Comment by Tor-Saxberg** [comment]
wasn't Luna supposed to be backwards compatible with Textractor plugins? I'm just reporting that the latest release is not. Is there a dll for chatgpt translator that works?

**Comment by HIllya51** [comment]
use it https://github.com/HIllya51/LunaTranslator

**Comment by HIllya51** [comment]
After testing, plugins can be loaded normally, it is you did't use plugins correctly, and I am not interested in teaching you how to use plugins.
