### ISSUE TITLE
There's a problem with the RPGMaker engine

### ISSUE THREAD

**Issue by Ivachnenco** [HIllya51/LunaHook#12]
Hello. Problem with RPGMaker engine. I noticed that Lunahook captures text exactly as it appears on the screen. That is, if there are several lines of text on the screen, it captures them separately even though it may be a whole sentence. This makes the translation look sloppy because it translates each line separately, not the whole text up to the point, i.e. the whole sentence. The same RPGMakerMVGame Hook patcher, for example, is perfectly capable of capturing the entire text of a sentence. In LunaTranslator the problem is the same. Sorry for my English, I am not a native speaker.
https://i.imgur.com/U2LAkDM.png

**Comment by HIllya51** [comment]
You can use Textractor's filter plugins to filter the space lines. I will not filter the space lines because space lines is important when embed the translation into the game.

**Comment by HIllya51** [comment]
In lunatranslator, it has so many build-in text process method, I think you can filter space lines so easy by your self.

**Comment by HIllya51** [comment]
In lunatranslator, it has so many build-in text process method, I think you can filter space lines so easy by your self.

**Comment by Ivachnenco** [comment]
A google search works wonders, I found a solution. https://github.com/Artikash/Textractor/issues/427. You need to insert the script of the respected Artikash into Lua and all the text starts to be displayed in one line. The topic can be closed, thank you for your attention
