### ISSUE TITLE
[not a bug] Enhancement: websocket sender

### ISSUE THREAD

**Issue by AuroraWright** [HIllya51/LunaHook#120]
### Version 程序版本

3.9.0

### Reproduction steps 复现步骤

In Japanese learning communities, it became common to use websockets to send text to a browser page to use yomitan with it (as an example, this page https://github.com/Renji-XD/texthooker-ui ). The advantage is that you don't spam the clipboard all the time. There are textractor plugins that do this (as an example, https://github.com/KamWithK/TextractorSender ) and they work with LunaHook, but maybe it would be useful to add a built-in "send to websocket" action other than "send to clipboard" so you don't need to use a plugin.

**Comment by HIllya51** [comment]
use https://github.com/HIllya51/LunaTranslator
