### ISSUE TITLE
CrossCode

### ISSUE THREAD

**Issue by Cloudstrifeff7** [HIllya51/LunaHook#124]
### vndb link/id

https://store.steampowered.com/app/368340/CrossCode/

### Game resource 游戏资源

You can find the demo here: https://store.steampowered.com/app/368340/CrossCode/

CrossCode is programmed in JavaScript, and makes use of a heavily-modified Impact engine which utilizes HTML5

https://impactjs.com/

### screenshot 截图

![image](https://github.com/user-attachments/assets/d89165f9-73e8-42fb-8fb3-1c2264d0ede5)

![image](https://github.com/user-attachments/assets/e67291fe-b0ba-45d4-aaf0-a717837b05a2)

![image](https://github.com/user-attachments/assets/f547def4-7342-46f2-875c-4d70ad1a6a9d)

**Comment by HIllya51** [comment]
give me resource rather than steam

**Comment by Cloudstrifeff7** [comment]
> give me resource rather than steam

https://1fichier.com/?d3fuc8a203hkebfvxaal

here the link

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-16 092557](https://github.com/user-attachments/assets/f28abcbe-928e-4cb4-99a8-65004ea6a002)

**Comment by HIllya51** [comment]
Can you please not disgust me?
![屏幕截图 2024-08-16 092616](https://github.com/user-attachments/assets/a9cbb3c1-e07c-4769-bd3e-27b55491b31d)

**Comment by HIllya51** [comment]
This is not a visual novel at all, and there's barely any text in it. 
Before asking questions, wear your eyes first.
Don't bother me with this kind of thing.
![屏幕截图 2024-08-16 094128](https://github.com/user-attachments/assets/1c0dd5c2-18a8-4cb6-aae7-56ba766506cb)

**Comment by Cloudstrifeff7** [comment]
Hey HIllya51, instead of insulting others because you can't solve the problem, you should learn to respect other people.
