### ISSUE TITLE
 Hey HIllya51, instead of insulting others because you can't solve the problem, you should learn to respect other people.

### ISSUE THREAD

**Issue by Cloudstrifeff7** [HIllya51/LunaHook#125]
Can you please not disgust me?
![屏幕截图 2024-08-16 092616](https://github.com/user-attachments/assets/a9cbb3c1-e07c-4769-bd3e-27b55491b31d)

_Originally posted by @HIllya51 in https://github.com/HIllya51/LunaHook/issues/124#issuecomment-2292552432_
            

Hey HIllya51, instead of insulting others because you can't solve the problem, you should learn to respect other people.

![cinese](https://github.com/user-attachments/assets/37a05df9-833f-43b5-ab19-6ab686083ff0)

![cinese2](https://github.com/user-attachments/assets/8f2cfa1d-ab06-4775-a6e4-c980ce5cfd66)

**Comment by HIllya51** [comment]
﻿
Who taught you to do whatever you want, not follow requirements, and ask random questions?
Firstly, shouldn't we read the readme at least once before asking questions?
Then, since there is a template for the problem, shouldn't we follow the requirements of the template?

**Comment by Cloudstrifeff7** [comment]
> Who taught you to do whatever you want, not follow requirements, and ask random questions? Firstly, shouldn't we read the readme at least once before asking questions? Then, since there is a template for the problem, shouldn't we follow the requirements of the template?

ot only do you insult others, but you’ve also copied the hooks/scripts from Textractor and Agent without giving credit. By the way, I’ve successfully extracted text from games like Yakuza 0 for PC, so it wasn't strange at all for me to ask about hooking from CrossCode. Anyway, I won’t be joining your Patreon. Instead, I'll be paying Agent directly for any future script commissions to extract text from games. Goodbye!

P.S. The truth is already known by me and others.

**Comment by HIllya51** [comment]
I have resolved nearly 1000 issues and have had a pleasant conversation with most of them. I only created this program out of interest, with almost no profit, so I don't think it's necessary for me to be unhappy because of someone like you.

**Comment by HIllya51** [comment]
are you "sekai"?

**Comment by HIllya51** [comment]
What is "stolen code from Textractor and Agent"? LunaHook is a 100% open source program. Can you teach me what is stolen?
I have also said directly in my reddit post before that this program is the successor of Textractor, and I also wrote in the readme that the program is compatible with the Textractor plugin. What on earth made you think that it was stolen?

**Comment by Cloudstrifeff7** [comment]
> What is "stolen code from Textractor and Agent"? LunaHook is a 100% open source program. Can you teach me what is stolen? I have also said directly in my reddit post before that this program is the successor of Textractor, and I also wrote in the readme that the program is compatible with the Textractor plugin. What on earth made you think that it was stolen?

I'm glad you've resolved many issues, but it doesn't change the fact that you’ve been taking credit for code that isn’t yours. Also, it's worth noting that you’ve been insulting people on a personal level. Just so you know, Agent, myself, and others in Agent’s Discord have already opened a ticket with the GitHub staff, reporting that you've been stealing others' code.

**Comment by HIllya51** [comment]
You are just talking to yourself the whole time, it's hilarious. I don't care what you think, I have no intention of making money with this software.

**Comment by HIllya51** [comment]
Many open source software have sponsorship links. This program has been open source for almost two years, but I only opened the patron about half a year ago, and it was because a Russian wanted to sponsor me, and I opened the patron under strong request. So far, I have only received a few dozen dollars. I think this is far less than the amount of work I have done for it. So don't you think your criticism is ridiculous?

**Comment by HIllya51** [comment]
If you mean agent, I remember it was a script written in js, and I rewrote the entire code in c++. This kind of porting has never been considered as infringement in any sense.

Moreover, scripts use the MIT license. If you don't allow others to port your code, why use the MIT license? It feels hypocritical.

**Comment by HIllya51** [comment]
You are hilarious, as if your little code is important to me. In fact, people who use this software hardly play games on the emulator platform. I just ported it for fun. I have not received any praise for this feature.

**Comment by HIllya51** [comment]
Finally, I want to tell you that your behavior is very funny to me. You seem to have no idea what open source is and what an open source agreement is. Most of my friends are from my country and they contribute most of my strength. You are just bragging here after enjoying it all.

**Comment by HIllya51** [comment]
Oh, by the way, I haven't paid attention to him for a long time since I completed the porting of scripts. Your issue reminded me to check it out.Thank you for the reminder, I will transplant it over immediately.

**Comment by AozoraDev** [comment]
> I'm glad you've resolved many issues, but it doesn't change the fact that you’ve been taking credit for code that isn’t yours. Also, it's worth noting that you’ve been insulting people on a personal level. Just so you know, Agent, myself, and others in Agent’s Discord have already opened a ticket with the GitHub staff, reporting that you've been stealing others' code.

![image](https://github.com/user-attachments/assets/51aa827b-c8d2-4688-a171-b0220f5b117f)

**Comment by HIllya51** [comment]
> ![image](https://private-user-images.githubusercontent.com/61007475/374639396-51aa827b-c8d2-4688-a171-b0220f5b117f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTM2NTAsIm5iZiI6MTcyODQxMzM1MCwicGF0aCI6Ii82MTAwNzQ3NS8zNzQ2MzkzOTYtNTFhYTgyN2ItYzhkMi00Njg4LWExNzEtYjAyMjBmNWIxMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE4NDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOGQ2MWI4NTI2OGY3YjAzYTFmMGQ3N2NhMTVkZGE5ZDVlNGEyNjhmN2M0ZDRjZjAxYzNhYWQwYWJjZjQ3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2-R6DXjO5nwsUI-vR2Rz3hh_GdGQjnpl9C0F5FDrfAI)
What do you want to say... ?
