### ISSUE TITLE
游戏文本没有显示

### ISSUE THREAD

**Issue by wite-666** [HIllya51/LunaHook#127]
### vndb link/id

https://www.alipan.com/t/Kn8Kk7vnBw0q8OfrWNFi

### Game resource 游戏资源

https://www.alipan.com/t/Kn8Kk7vnBw0q8OfrWNFi

### screenshot 截图

![V$UL8QICRHWEU~)$NFLUB~M](https://github.com/user-attachments/assets/2937c8bf-23f0-4911-89ca-8033b51675ba)
![V$UL8QICRHWEU~)$NFLUB~M](https://github.com/user-attachments/assets/16f55bff-7c58-41c2-af01-8d4157ac0c0d)

**Comment by HIllya51** [comment]
![6152F48A8C67780B179CDF9176E9C039](https://github.com/user-attachments/assets/0298456f-dd18-4dda-9d33-5eaeb22c615c)
