### ISSUE TITLE
Applique and 	Akatsuki WORKS hook error Tsukikage no Simulacre 

### ISSUE THREAD

**Issue by NONAMEHP** [HIllya51/LunaHook#128]
### vndb link/id

https://vndb.org/v19964

### Game resource 游戏资源

I'm having trouble with Applique and Akatsuki WORKS games because they don't hook text correctly. Now I've been getting errors like this on:
Tsukikage no Simulacre
Hi no Nai Tokoro ni Kemuri wa Tatanai
Suisei Ginka all have the same error as shown in the picture
https://vndb.org/v20227
https://vndb.org/v19964
https://vndb.org/v19369
I hope you can help me fix errors in this company's games

### screenshot 截图

![Screenshot 2024-08-19 163326](https://github.com/user-attachments/assets/49427bcf-e0c4-4e55-a2c6-470d5d5a820d)
![Screenshot 2024-08-19 163354](https://github.com/user-attachments/assets/f8a4dc42-5caa-48d7-881b-610b883f5a3e)

**Comment by HIllya51** [comment]
😅

**Comment by HIllya51** [comment]
I really dislike people who don't ask questions as required.
Please fill in 'Game Resources' correctly and ask again.

**Comment by HIllya51** [comment]
There's nothing wrong with the text at all, you just haven't set up the filter correctly.
see document https://docs.lunatranslator.org/#/zh/textprocess

**Comment by NONAMEHP** [comment]
Thank you for your guidance, I solved my problem and will pay attention next time
