### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by UESTC-LXY** [HIllya51/LunaHook#13]
error C3861: “PyUnicode_Check”: 找不到标识符 
error C3861: “PyUnicode_IS_READY”: 找不到标识符
...

**Comment by HIllya51** [comment]
使用的什么版本的编译器

**Comment by HIllya51** [comment]
确实是忘了把这几个符号复制进来了，不过是因为在vs2022 msvc143上没有报错所以才忘了复制，所以这个并没有影响。如果你发生了编译错误，请使用更新版本的编译。

**Comment by HIllya51** [comment]
你可能是自己手动cmake用了debug模式，改成release就行了

**Comment by UESTC-LXY** [comment]
嗯嗯 我用的是14.39.33519 已经很新了，改成release好了，感谢
