### ISSUE TITLE
Seijun na Karada wa, Aitsu no Ude no Naka de Otoko o Shitteiku -Kanojo no Shiawasesou na Sugata o, Yubi o Kuwaete Miteirushika Nai Monogatari

### ISSUE THREAD

**Issue by Solanastar** [HIllya51/LunaHook#130]
### vndb link/id

https://vndb.org/v5688

### Game resource 游戏资源

https://drive.google.com/file/d/1roWuz1DLlBJ9U0pCleFNhBdjD6uKMr2_/view?usp=sharing

### screenshot 截图

![image](https://github.com/user-attachments/assets/9d73ab71-b3b9-4b98-a33e-7cf31e88bcd9)

**Comment by HIllya51** [comment]
😅
![屏幕截图 2024-08-28 175238](https://github.com/user-attachments/assets/db352718-cd1f-4eaf-a4f7-902da6b6f44d)

**Comment by Solanastar** [comment]
> 😅 ![屏幕截图 2024-08-28 175238](https://private-user-images.githubusercontent.com/101191390/362232264-db352718-cd1f-4eaf-a4f7-902da6b6f44d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTk0NzMsIm5iZiI6MTcyNDg5OTE3MywicGF0aCI6Ii8xMDExOTEzOTAvMzYyMjMyMjY0LWRiMzUyNzE4LWNkMWYtNGVhZi1hNGY3LTkwMmRhNmI2ZjQ0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwMjM5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzMyYTllMTJiNjc4YjNmZWViMmQyYzVkNjZmODlkMjQ2OWEyYTRiMzIxNWI2YWNlYTUyMzA4ZjJhMTYyNGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G0f8-YquA3TF62KyF-M6BVtobuuXay4ydhMV1hb4Hzs)

Is this the start of the game?
I think it's my fault for not explaining it well
the first lines of dialogue work normally but after a few dialogues it looks like the image i sent above
and the rest of the game looks like that
Can you take another look at this?
just to be sure is not only me that have this problem.

**Comment by HIllya51** [comment]
Before asking such question, you should upgrade to the latest version
