### ISSUE TITLE
没有文本

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#131]

**Comment by HIllya51** [comment]
我w11直接能运行，就是有点错位。文本也直接就有。

![屏幕截图 2024-08-29 193509](https://github.com/user-attachments/assets/63ad6ced-783c-4a47-9850-261dc85c2ff6)

3.8版本在winxp上好像不能正常工作，你更新一下就好了。

**Comment by qscasdasd** [comment]
> 我w11直接能运行，就是有点错位。文本也直接就有。
> 
> ![屏幕截图 2024-08-29 193509](https://private-user-images.githubusercontent.com/101191390/362665934-63ad6ced-783c-4a47-9850-261dc85c2ff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzM3ODUsIm5iZiI6MTcyNDkzMzQ4NSwicGF0aCI6Ii8xMDExOTEzOTAvMzYyNjY1OTM0LTYzYWQ2Y2VkLTc4M2MtNGE0Ny05ODUwLTI2MWRjODVjMmZmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMjExMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjFkZjhiZTNkMGVkOTBiMzNhNDJlMzc3MWYzOWNkNWYzZjkyZDNiNzcwYzNiY2E3YjBmNzdkZWE5NjlmNjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pcCD3sbXzLCHi5B8-iVkTDr0HixZYPuYvOGNHFGpWlM)
> 
> 3.8版本在winxp上好像不能正常工作，你更新一下就好了。

3.10也是一样的报错，可能我电脑有问题吧，这作先弃了
