### ISSUE TITLE
Support for Monster Girl Quest Remastered, a version of OnScripter

### ISSUE THREAD

**Issue by BlindGuyNW** [HIllya51/LunaHook#133]
### Game resource 游戏资源

https://drive.google.com/file/d/1Dcypl699PePZMbFkqN_Domn-rBiGaf9s/view

### screenshot 截图

This game uses a version of Onscripter but isn't detected by the engine hook search. The original MGQ uses a different engine which suffers from the same problem.

Thanks for the help.

**Comment by HIllya51** [comment]
HB-10*0@50C94:Monster Girl Quest Remastered.exe
