### ISSUE TITLE
Game text not appearing in the select text area.

### ISSUE THREAD

**Issue by Nuhabaka** [HIllya51/LunaHook#134]
### Game resource 游戏资源

Dystopia no Ou, physically bought.

### screenshot 截图

<img width="494" alt="Screenshot 2024-09-04 190936" src="https://github.com/user-attachments/assets/1aae185a-1491-4a8c-bba0-d0b108329beb">

**Comment by HIllya51** [comment]
Are you joking? Do you want me to buy a game?

**Comment by HIllya51** [comment]
tested on trial version, worked fine.
![屏幕截图 2024-09-05 093821](https://github.com/user-attachments/assets/5d50db0a-ee39-4f00-b19d-c632e7575098)
