### ISSUE TITLE
无文本

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#135]
### vndb link/id

https://vndb.org/v12860

### Game resource 游戏资源

https://mega.nz/file/1CtnyC4A#mWvF-qWqTG8oGdHi1LAMBemg1h4KXTIrX5--FI3oPFA

### screenshot 截图

![QQ20240907-170716](https://github.com/user-attachments/assets/b4004930-29bd-48fc-b9b5-8877ded73686)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/100ed89542fb84dd3546ba5fa141d2986b69176f
