### ISSUE TITLE
hook文本缺失

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaHook#136]
### vndb link/id

https://vndb.org/v8528

### Game resource 游戏资源

https://mega.nz/file/gOkxiYxL#JLeZ9hQsXf3HyrJDjjKgKMBWNFTMFL3Xjf5gI-IolSg

### screenshot 截图

![QQ20240907-194149](https://github.com/user-attachments/assets/44cd4f10-9e6d-465c-97e9-de734bc9e200)
只有汉字

**Comment by HIllya51** [comment]
这个要怎么运行。。。

**Comment by dnadash** [comment]
> 这个要怎么运行。。。

兼容模式win98安装，运行

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/06f134e87a6e5cce22c51f2a158eba676d6fd133
