### ISSUE TITLE
星之梦法语版识别不正常

### ISSUE THREAD

**Issue by Stillily** [HIllya51/LunaHook#137]
### vndb link/id

https://vndb.org/r9731

### Game resource 游戏资源

https://drive.google.com/file/d/1LVp16IPbtn50gTT4Zkn03ynXsD4EwAJL/view?usp=sharing
解压后要安装目录里的sazanami-gothic.ttf

### screenshot 截图

![image](https://github.com/user-attachments/assets/8000d9d6-6446-43eb-a1b3-ab61a9aaea36)

**Comment by HIllya51** [comment]
不是，你为什么要用法语版的？

**Comment by Stillily** [comment]
哈哈，玩gal还能练外语我感觉很爽
帮帮忙嘛，或者告诉我思路也行，看这样子应该是抓到hook了调整一下输出就行了

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/20ce1fa8d040e93d69c807f9c372be46932826d5
