### ISSUE TITLE
无法获取文本

### ISSUE THREAD

**Issue by LugaDX** [HIllya51/LunaHook#138]
### vndb link/id

WORDS WORTH【Windows10対応】

### Game resource 游戏资源

https://drive.google.com/file/d/16S8yN1q0nJyNqPbjeMzcJpQElU0yvQ76/view?usp=sharing

### screenshot 截图

![选择文本](https://github.com/user-attachments/assets/59eb1054-c28d-4b22-918f-3f90131f631d)
![游戏图片](https://github.com/user-attachments/assets/5743f0c8-9d5a-4c1c-83ee-59fda033c19a)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/5ef325d64d4381ba7f96c1f95da158545768dce0
