### ISSUE TITLE
文本不正确，多字，乱

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#139]
### vndb link/id

https://vndb.org/v5864

### Game resource 游戏资源

https://mega.nz/file/IC031RxR#cK1y-hIvBHIvp_9Sgn98tOMid-GFbFxNMvqU5x50vD8

### screenshot 截图

![屏幕截图(4072)](https://github.com/user-attachments/assets/c9106a02-bf5d-46e8-96ba-66d7a739b3e5)
安装完提示的音频播放器后，直接从光驱里双击启动游戏，转区会乱码。游戏强制全屏，不过不影响提取文本

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/6ff92740b7c0ef451b6824e39d46f3bf79159ea1
