### ISSUE TITLE
希望面板添加选中复制功能

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaHook#14]
![QQ图片20240419192204](https://github.com/HIllya51/LunaHook/assets/61865659/759c1036-f73f-4a7a-a7cc-63387f92e866)
希望面板添加选中复制功能，像Textractor那样，方便遇到不懂的词语复制粘贴去查词

**Comment by HIllya51** [comment]
Textractor哪有这个功能？

**Comment by HIllya51** [comment]
什么莫名其妙的

**Comment by k2250761** [comment]
https://github.com/HIllya51/LunaHook/assets/61865659/3f9d3d3c-12da-4072-aabe-a19bae282796

**Comment by k2250761** [comment]
![GIF 2024-4-19 19-46-38](https://github.com/HIllya51/LunaHook/assets/61865659/18f1bfb1-384a-4fc5-9d8a-b4d99c99d43e)

**Comment by HIllya51** [comment]
这又不是一个非常频繁的操作，你手动ctrl c一下不行吗，又不麻烦。用win32很难实现这玩意儿。

**Comment by HIllya51** [comment]
加也不是不行，不过为了省事可能做到比较丑陋

**Comment by k2250761** [comment]
> 加也不是不行，不过为了省事可能做到比较丑陋

没事，能用到就行，其他不奢求
