### ISSUE TITLE
文本缺假名

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#140]
### vndb link/id

https://vndb.org/v2274

### Game resource 游戏资源

https://mega.nz/file/5S9mkRjD#E-qBmnfgQ8-uIjOfedUdEOd9_kbbjxQWP7-SpdVgnIY

### screenshot 截图

![QQ20240910-191704](https://github.com/user-attachments/assets/6402a675-3480-402e-bab0-33eadf35da59)
最好兼容XP启动游戏，直接启动的话好像会卡OP

**Comment by HIllya51** [comment]
安装不了

**Comment by qscasdasd** [comment]
> 安装不了。给我nodvd补丁。。。

把光驱里文件复制出来，把这个安装程序放在一起，转区运行
![1](https://github.com/user-attachments/assets/090c89ae-c4ac-47a5-94cd-bc4be0a15605)
安装程序下载https://mega.nz/file/IDMmHRSa#UqUlma_vMKAJAzolOEKAAMaArRRjUpnQG5Fs2fA4L14

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/b13a4240abaa8bbfa8770c2b9d9b31f10cbc1a6e
