### ISSUE TITLE
King Exit

### ISSUE THREAD

**Issue by Shisha22s** [HIllya51/LunaHook#141]
### vndb link/id

https://vndb.org/v25420

### Game resource 游戏资源

[google drive](https://drive.google.com/file/d/1D7z6lbYOqCXnZl4x9uFZLAMhOr1HMss3/view?usp=drive_link)

### screenshot 截图

main thread https://github.com/HIllya51/LunaTranslator/issues/1063

![1](https://github.com/user-attachments/assets/1bc9893f-2317-4a8c-a449-37606e4547f4)
![2](https://github.com/user-attachments/assets/00a1e73c-e094-447e-a04e-514d92e298b0)
![3](https://github.com/user-attachments/assets/97090739-307c-4388-8d0b-b2c1d72c4c29)
![4](https://github.com/user-attachments/assets/cbe756c1-7800-4775-8c9f-41fbf9e2db4f)
![5](https://github.com/user-attachments/assets/8f7a506c-803e-4e52-86e2-29bf0b7a57b2)
![6](https://github.com/user-attachments/assets/d619b960-9d4f-4027-9604-7432456e2501)

**Comment by HIllya51** [comment]
use this hookcode: HVN4:10*0@100415B0
