### ISSUE TITLE
奴隷ハーレム解放戦線v1.06 文本识别不全或识别后无法自动翻译

### ISSUE THREAD

**Issue by sun1a2b3c** [HIllya51/LunaHook#142]
### vndb link/id

奴隷ハーレム解放戦線v1.06

### Game resource 游戏资源

游戏内在地图上的房间访问后触发对话、在间章的商店购买商品、剧情CG演绎及支线任务对话都出现了翻译不全或没有翻译的问题（内嵌字幕没有覆盖）。游戏过程中有用到小黄鸭来进行超分辨率缩放和补帧，不知道对翻译有没有负面影响？
https://1drv.ms/u/s!AhFd5u_-ePckiqcMl6TgJ8Of36Y0XA?e=4VaZTI

### screenshot 截图

<img width="601" alt="屏幕截图 2024-09-10 203656" src="https://github.com/user-attachments/assets/baa922aa-c02d-4a1f-a0e0-b485e6454ee9">
<img width="902" alt="屏幕截图 2024-09-10 203708" src="https://github.com/user-attachments/assets/513f0a0c-3dad-449c-a053-a15f7d1cdc2f">

**Comment by HIllya51** [comment]
那就不要内嵌。

**Comment by HIllya51** [comment]
rpg内嵌是个很麻烦的事，没有兴趣处理内嵌不正确的问题。如果一定要内嵌翻译玩rpg，可以使用mtool。
