### ISSUE TITLE
Little Busters! Converted Edition for Switch

### ISSUE THREAD

**Issue by BlindGuyNW** [HIllya51/LunaHook#143]
### vndb link/id

https://vndb.org/r19841

### Game resource 游戏资源

Little Busters! converted edition is not currently supported. The NSP can be downloaded from GDrive at https://drive.google.com/file/d/1TROhbe6zLH9nHX_-GafIfuUrYiFKJUIZ/view?usp=sharing

When using LunaHook I see the following.

Attach engine yuzusuyu success and stop
Little Busters! Converted Edition 100943010310000 1.0.0

Thanks for helping with this. :)

### screenshot 截图

N/A

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/6453c704c3ae5e728aecda893223a20d71117ea3
