### ISSUE TITLE
In by side

### ISSUE THREAD

**Issue by SHRIMP159** [HIllya51/LunaHook#144]
### vndb link/id

https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_241032/?dmmref=ListRanking&i3_ref=list&i3_ord=1

### Game resource 游戏资源

https://mega.nz/file/8ZZgCLyL#NU_3EA9SElOR596wtvhKHjB1yVkropiTO15RGDt_8bg

Sentence is truncated and printed.

A. ここの職員採用は所長の裁量に任されていたから、学校を卒業したばかりの自分でも雇っても
らうことができた。​

B. ここの職員採用は所長の裁量に任されていたから、学校を卒業したばかりの自分でも雇ってもらうことができた。

The sentence should be connected like B, but the translator can't translate it properly because it's cut off and printed like A.

P.S Luna Hook is so cool!

### screenshot 截图

![1](https://github.com/user-attachments/assets/602c0af1-7563-4884-ad4f-5210e2501616)

**Comment by SHRIMP159** [comment]
It's the WOLF RPG game.

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/textprocess

Filter out line breaks yourself.

**Comment by SHRIMP159** [comment]
Is there any way I can handle it in Luna Hook?

deepl or papago translator does not work with LunaTranslator.
