### ISSUE TITLE
缺字

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#145]
### vndb link/id

https://vndb.org/v1334

### Game resource 游戏资源

https://mega.nz/file/JOE1gS7Q#PgfBolqSZiV5SF5nzKdK1wSe8mluUElBA833UiBO2C8
https://mega.nz/file/db8UkTga#62VmWl5CUSkqRWIvsscxvPEI__1_3t3-mdmqnUq2aqw
https://mega.nz/file/kaFFmKZC#yRR4uXpJ_xHYs8S8qep1_snxjPk73bvjWOCe9ptoFxM
三个分卷，一共2G

### screenshot 截图

![QQ20240913-013907](https://github.com/user-attachments/assets/efbad584-4532-4378-bb28-f4c8a70d71a2)
游戏安装挺慢的，要等会儿。这游戏看了下没有符号，框之类的可以过滤人名，不知道露娜佬能不能在添加的HOOK里直接过滤掉人名

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/3b2a0f7f22abb7cf583dd4fb042527b74f2ed040
