### ISSUE TITLE
ネクロマリア

### ISSUE THREAD

**Issue by fatecyx** [HIllya51/LunaHook#146]
### Game resource 游戏资源

https://drive.google.com/file/d/1UPE4BxefTSE2bk64Ab1OM6eJELr7LQpW/view?usp=drive_link

### screenshot 截图

文本很难找，有一次好像搜到文本了，但是重启以后复制的特殊码就失效了，然后又找不到了

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/39d2a81f4da8f18dff1f91c2759b10fd508700dd

**Comment by fatecyx** [comment]
> [39d2a81](https://github.com/HIllya51/LunaHook/commit/39d2a81f4da8f18dff1f91c2759b10fd508700dd)

文本里面的换行符可以保留吗，

**Comment by HIllya51** [comment]
我一般不会在hook内把换行符过滤掉，如果没有换行符说明没有提取到换行符



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 17, 2024 01:43 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HIllya51/LunaHook] ネクロマリア (Issue #146)




  
39d2a81
  
文本里面的换行符可以保留吗，
