### ISSUE TITLE
无法过滤人名

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#148]
### vndb link/id

https://vndb.org/v540

### Game resource 游戏资源

https://mega.nz/file/0TNn0R5A#2F3ysTlIpx899DVM5K50aI4I65jaUa-XQ9hBzxUId2A

### screenshot 截图

![QQ20240915-200723](https://github.com/user-attachments/assets/22b70e14-646b-4581-9507-780fb341cb77)
能否单独添加HOOK省去人名

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/4fc9e5232e300adef5459be466a9aede4323865c
