### ISSUE TITLE
Little Busters EX! is not getting any text after hooking

### ISSUE THREAD

**Issue by inf1425** [HIllya51/LunaHook#149]
### vndb link/id

https://vndb.org/r1944

### Game resource 游戏资源

https://gofile.io/d/EuSzG5

### screenshot 截图

![image](https://github.com/user-attachments/assets/d82f0739-dce5-42b0-8c19-42614ec46202)

The game gets hooked, and engine is recognized, but no text gets extracted. It used to work in an older version of LunaHook but I can't check which version, because only the latest release is available on GitHub.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/950171030c15b9767e64154f0d0de7f979441de6
I'm sure it is impossible to work before.
