### ISSUE TITLE
[Feature request] Launch game / Emulate Japanese locale

### ISSUE THREAD

**Issue by SnowLynnx** [HIllya51/LunaHook#15]
In Textractor, when you use "Launch game" button, it asks you if you want to emulate Japanese locale. Most of untranslated Japanese VNs won't launch or will have issues without Japanese locale so this feature is very useful for me because I don't need to do any manipulations in Windows settings or use some separate tool to emulate Japanese locale.
Would be great to have it in LunaHook as well.

**Comment by HIllya51** [comment]
It is just using [Locale-Emulator](https://github.com/xupefei/Locale-Emulator) to launch game.
I don't want to use this program to launch game. 
I think you can direct use Locale-Emulator by yourself.

**Comment by HIllya51** [comment]
And Locale-Emulator only support 32 bit program. 
Locale-Emulator has been built-in in [LunaTranslator](https://github.com/HIllya51/LunaTranslator) and LunaTranslator support use Locale-Emulator/Locale_Remulator/NTLEA to launch 32 bit and 64 bit games。
LunaHook is only a Text Hook engine and I don't want to add so much unrelated features in it. The more advanced features have been add in LunaTranslator.
