### ISSUE TITLE
Majikoi! Love Me Seriously!

### ISSUE THREAD

**Issue by IOmar24** [HIllya51/LunaHook#150]
### vndb link/id

https://vndb.org/v1143

### Game resource 游戏资源

https://8fl2fw-my.sharepoint.com/personal/misakichan_digitalshop_biz_id/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmisakichan%5Fdigitalshop%5Fbiz%5Fid%2FDocuments%2Fr64729&ga=1

### screenshot 截图

![Majikoi! Love Me Seriously! 22_09_2024 14_23_47](https://github.com/user-attachments/assets/980a0181-ae82-43fd-8dd4-76ffd95ff7cf)
![Select Text 22_09_2024 14_23_36](https://github.com/user-attachments/assets/5788ab91-b061-41cd-887c-8fb2f802c126)
![Majikoi! Love Me Seriously! 22_09_2024 14_22_01](https://github.com/user-attachments/assets/b70560fc-b646-45ec-9c0e-2be2a8dc1b02)

**Comment by HIllya51** [comment]
invalid link

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/3ea04fd36b5f2977a5b9cab8018460f1a7357490
