### ISSUE TITLE
Fortissimo FA INTL Ver

### ISSUE THREAD

**Issue by NONAMEHP** [HIllya51/LunaHook#151]
### vndb link/id

https://vndb.org/v7595

### Game resource 游戏资源

https://drive.google.com/file/d/1u9_T9mO1Wz00xrxVCe1W837Hhxr7syaO/view?usp=sharing

### screenshot 截图

<img width="1214" alt="Untitled" src="https://github.com/user-attachments/assets/99cb2443-1327-4910-a76e-a800b99cdc0a">
Fortissimo FA INTL Ver (Chinese simplified) hook not found
Please help me .

**Comment by HIllya51** [comment]
😅

**Comment by HIllya51** [comment]
Why did you give me a link to the English version and asked for support for the Chinese version?
Why did you give me a website full of ads? I saw more than a dozen ads but still couldn't get a download link.

**Comment by HIllya51** [comment]
After wasting a lot of time to finally get the link and download it, I only got such an invalid file.🙃

![屏幕截图 2024-09-23 174217](https://github.com/user-attachments/assets/53b51a3b-2db2-4359-8673-0659cab12740)

**Comment by NONAMEHP** [comment]
you have facebook ? ib me and i give you steam account have game
<img width="1280" alt="Untitled" src="https://github.com/user-attachments/assets/5553bc47-f157-47a3-9ec1-0f60d14b461a">

**Comment by NONAMEHP** [comment]
Because neither the English nor the Chinese nor the Japanese can find the hook, I think if you can find the hook in the English version, the Chinese and Japanese versions can also find it.
<img width="768" alt="Untitled" src="https://github.com/user-attachments/assets/e23d39c1-80dd-4e8f-84f8-12f19ec36ab3">

**Comment by NONAMEHP** [comment]
wait me download japanese vesion and uploading google driver for you

**Comment by HIllya51** [comment]
![屏幕截图 2024-09-24 105205](https://github.com/user-attachments/assets/42e6996f-e919-44b9-bb5e-523017c12a21)
