### ISSUE TITLE
无法提取文本

### ISSUE THREAD

**Issue by loperot504** [HIllya51/LunaHook#152]
### vndb link/id

女系家族 ～淫謀～ＤＬ版

### Game resource 游戏资源

https://drive.google.com/file/d/1N4qtSH59r9oCLFAKtTEoD9sO8_3MjX9T/view?usp=sharing

### screenshot 截图

![屏幕截图 2024-09-24 003556](https://github.com/user-attachments/assets/c0d0fabf-540f-42be-9b2b-58bee9e3f073)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/fa654f80027dd9977d5bd8ad468f87bffdc57f17
