### ISSUE TITLE
请求对mkxp-z引擎支持（以Pokémon Reminiscencia为例）

### ISSUE THREAD

**Issue by gmgorag** [HIllya51/LunaHook#154]
### Game resource 游戏资源

https://mega.nz/file/kx01XbCQ#GOqREXWHqrC7mNNjGYEUmKCkqO3L5F9z2mqGbsi--yA

### screenshot 截图

<img width="1130" alt="1" src="https://github.com/user-attachments/assets/7540f224-c9cf-4dcf-b26d-0205f30bb7da">

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/3eaa545f99341281645ca0f76e72c00eaa5c8903
