### ISSUE TITLE
女装山脉

### ISSUE THREAD

**Issue by Sunshine426** [HIllya51/LunaHook#155]
### vndb link/id

https://vndb.org/v6589

### Game resource 游戏资源

https://www.shinnku.com/human?redirect=/api/download/raw3/2011%E5%B9%B46%E6%9C%88/[110617][%E8%84%B3%E5%86%85%E5%BD%BC%E5%A5%B3]%20%E5%A5%B3%E8%A3%85%E5%B1%B1%E8%84%88%20(mdf+mds+rr3).rar

### screenshot 截图

![Uploading a8fdaf06-2060-452c-9ce7-771087ee5083.png…]()

**Comment by HIllya51** [comment]
?
![屏幕截图 2024-10-03 180943](https://github.com/user-attachments/assets/0c032920-3405-4224-98db-9322de1bbe12)
