### ISSUE TITLE
Luna can't hook text in PPSSPP

### ISSUE THREAD

**Issue by noideaforeal** [HIllya51/LunaHook#156]
### vndb link/id

https://vndb.org/v3531#main

### Game resource 游戏资源

https://drive.google.com/file/d/1G11tmLY-7AGfBTJIA1yoK0ZO_t4xM_Gh/view?usp=sharing

### screenshot 截图

![image](https://github.com/user-attachments/assets/5fa3c336-0778-46fb-8f23-d2fbb2990511)

**Comment by HIllya51** [comment]
update to latest before create issue please.
![屏幕截图 2024-10-04 214511](https://github.com/user-attachments/assets/7da31fcd-52e2-4741-9089-f51c82ffd5e5)
