### ISSUE TITLE
Sorcery Jokers English version cannot find hook

### ISSUE THREAD

**Issue by Excaliburxxa** [HIllya51/LunaHook#157]
### vndb link/id

https://vndb.org/v16337

### Game resource 游戏资源

https://drive.google.com/file/d/1twPzctzfFyCCUiGGrSRke7uBUaZlCPjp/view

### screenshot 截图

![Screenshot 2024-10-08 155114](https://github.com/user-attachments/assets/82ea1453-66be-4507-9c03-68005f67c5c4)
I can't find the hook to play this game in the English version.  Please help me.  Download, unzip and run the setup file to install the game before you can play

**Comment by HIllya51** [comment]
the first line is the correct hook. use the textprocess to filter the dumplicate characters.
https://docs.lunatranslator.org/#/en/textprocess

**Comment by Excaliburxxa** [comment]
Generally, some problems have been fixed, but there will still be sentences like this.
![Uploading Screenshot 2024-10-08 175640.png…]()

**Comment by Excaliburxxa** [comment]
![Screenshot 2024-10-08 175640](https://github.com/user-attachments/assets/a87c06db-a793-4c00-a68a-e0d023698e71)

**Comment by HIllya51** [comment]
increase the "Maximum Buffer Length"

**Comment by Excaliburxxa** [comment]
thank you > It works
