### ISSUE TITLE
ANIM.teamMM Games hook

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaHook#158]
### Version 程序版本

3.14.0

### Related screenshot (optional) 相关截图（可选）

![Screenshot 2024-10-12 145330](https://github.com/user-attachments/assets/12d2ced1-bc1b-4d9b-bf93-18d2757f1eca)
![Screenshot 2024-10-12 145717](https://github.com/user-attachments/assets/25829deb-592c-41f6-8bf5-48d363e233ca)

### Reproduction steps 复现步骤

In the images above it says it's found a corresponding hook to the game ([https://vndb.org/v19463](https://vndb.org/v19463)), but the only two hooks that are available are both GetGlyphOutlineA.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml
