### ISSUE TITLE
Omertà ~Chinmoku no Okite~ The Legacy 

### ISSUE THREAD

**Issue by DarkVN101** [HIllya51/LunaHook#159]
### vndb link/id

https://vndb.org/v5243

### Game resource 游戏资源

https://www.mediafire.com/file/q97y4p0r9ilc9z6/%25E3%2582%25AA%25E3%2583%25A1%25E3%2583%25AB%25E3%2582%25BF_%25EF%25BD%259E%25E6%25B2%2588%25E9%25BB%2599%25E3%2581%25AE%25E6%258E%259F%25EF%25BD%259ETHE_LEGACY.7z/file

### screenshot 截图

![2024-10-20_174723](https://github.com/user-attachments/assets/dab66332-da49-4ec1-b07b-53bc90b0aea7)

分かってる……それにしても、今までに増して酷い部屋だな……  "増増酷酷屋屋梓梓梓" this is garbage text

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/7c2055e8a250a0f19e698c21f75baf6ccd56adf0
