### ISSUE TITLE
关于【编辑 翻译记录】功能的疑问

### ISSUE THREAD

**Issue by 555666233** [HIllya51/LunaHook#160]
我是自己本地翻译好游戏译文，然后转换为符合标准格式的json翻译文件，游玩时直接读取于预翻译文件里json翻译文件的已翻译文，这样就相当于汉化补丁那样以后都能直接游玩，也不用受限于游戏引擎的封包难题，一招吃遍所有galgame游戏。

因为AI翻译出来的译文时常有一些小问题，比如”我你他她“这样的小错误，还有偶尔的翻译质量不佳，只有一边玩时才能发现，所以需要随手修正。我看软件有一个【编辑 翻译记录】的功能，里面也能选择json翻译文件的来源并也能显示出来当前的译文，只是手动修改过后按下确定并不能同步修改json翻译文件的对应译文，只是在软件文本窗口里原本的译文下方多出了一条修正过的译文而已。

我不知道是不是我理解错了还是这个功能出了bug，如果是我理解错了这个功能的用法，那能否请大大为这个功能增加同步修改原json翻译文件的效果，实现一边玩一边顺便完善本地预翻译文本质量的效果？

修改前：
![screenshot-1729642339351](https://github.com/user-attachments/assets/5b8ff67a-7106-4867-847b-b4e759b09798)

修改后：（原本地json文本内容并无被修改）
![screenshot-1729642358745](https://github.com/user-attachments/assets/9610231c-d24f-4c17-84ba-8ff3625552aa)

**Comment by HIllya51** [comment]
你理解错了，这个东西只是修改的translation_record/下的sqlite记录。
而且json是明文的，你完全可以自己开记事本随时修改，没有做的必要。

**Comment by HIllya51** [comment]
你修改的记录会被记录到游戏的sqlite记录里。
如果你打开了sqlite预翻译，那么如果读取到相应的记录，会优先使用sqlite记录代替其他翻译，包括json预翻译。
最后，可以把sqlite记录导出其中你编辑的json预翻译的记录，用导出的记录update原来的json，这样可以达到相同的目的，不过会稍微麻烦一点。

**Comment by HIllya51** [comment]
可
