### ISSUE TITLE
有没有什么方法可以去掉文本上方的汉字，以便更准确地翻译？(	BALDR HEART)

### ISSUE THREAD

**Issue by Excaliburxxa** [HIllya51/LunaHook#161]
### vndb link/id

https://vndb.org/v18783#main

### Game resource 游戏资源

https://drive.google.com/file/d/1XsLAAwk8-dUIKXC31q3NIohJ6vw6EF_g/view?usp=sharing

### screenshot 截图

![Screenshot 2024-10-23 201514](https://github.com/user-attachments/assets/abf6e109-ab71-4708-9a3e-7fb224917568)
不仅是这个游戏，很多其他游戏也遇到过这个问题。如果你有可行的解决办法，请帮助我。

**Comment by Excaliburxxa** [comment]
![Screenshot 2024-10-23 202350](https://github.com/user-attachments/assets/146f6773-e535-4e9f-af39-5cfec8835886)

**Comment by HIllya51** [comment]
下载链接无效。

**Comment by Excaliburxxa** [comment]
https://drive.google.com/file/d/1XsLAAwk8-dUIKXC31q3NIohJ6vw6EF_g/view?usp=sharing
请再次使用这个链接

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/351100028fd98c0be0f99e0c1346a944929e682f

**Comment by Excaliburxxa** [comment]
它在 Lunahook 上运行良好，所以也请在 LunaTranslator 上更新它。 
太感谢你了
