### ISSUE TITLE
Include character name hooking

### ISSUE THREAD

**Issue by Igoorx** [HIllya51/LunaHook#163]
### vndb link/id

The game I'm translating is: https://vndb.org/v9208
However, this is a more general feature that theorically should work in any game.

### Game resource 游戏资源

I noticed that your previous instance about hooking names is that it's meaningless (https://github.com/HIllya51/LunaTranslator/issues/987#issuecomment-2286493662), but that's actually not true for LLMs (Large Language Models, like ChatGPT), because names are important context for a more accurate translation. So I was wondering if it would be possible to hook the character name so it could be included in the LLM prompt. Thanks in advance!

Example:
```
迪希: 「あははっ、一年分甘えさせてあげないと駄目よ？」
恂: 「ああ」
```

### screenshot 截图

![image](https://github.com/user-attachments/assets/2b73318f-9089-4094-a4dd-8db7b1637bd3)
( This screenshot shows that the name is already apparently visible in the Hooks list, but it has a lot of garbage with it)

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/textprocess

**Comment by Igoorx** [comment]
@HIllya51 😭 😭 
这不是问题。我猜想你听不懂英语？抱歉打扰了。你看，在KiriKiri2中，或者至少是在我玩的这个游戏里，钩子（hook）中并没有包含正确显示的角色名字，而是显示乱码。角色名字似乎在第二个钩子中被包含了，但是那里面也有乱码，似乎并不是一个好的钩子可以使用，例如：  
```迪希「「ごめん、まだわからないの。家・の・ほ・う・で何かあるかもしれな「ごめん、まだわからないの。家のほうで何かあるかもしれいし…。今、ちょっと葵あおいにメール送るから、合わせて聞ないし……。今、ちょっと葵にメール送るから、合わせていておくね」聞いておくね」```  
还是说，你的意思是上面这行可以通过文本处理来拯救？
