### ISSUE TITLE
sol-fa-soft社最后一弹！

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaHook#20]
### vndb link/id

5173

### Game resource 游戏资源

通过前两次更新和之前的底子，亲测该社游戏已经全部搞定，除了这唯一一款
https://drive.google.com/file/d/1rU5c5e86tpr79Bz1fQef3kAwtfi8DkDa/view?usp=sharing

**Comment by HIllya51** [comment]
done
