### ISSUE TITLE
Cannot find hook, for three games.

### ISSUE THREAD

**Issue by churroloca** [HIllya51/LunaHook#24]
### vndb link/id

https://vndb.org/v856

### Game resource 游戏资源

https://dlsoft.dmm.co.jp/detail/stone_0031/ first game

https://dlsoft.dmm.co.jp/detail/stone_0022/ second game
^^^^^^^
https://vndb.org/v1928

Both games only have hooks that get half the words and that's it. I can't seem to use any plugins on LunaHook either.

I'd greatly appreciate any advice or suggestions.

**Comment by HIllya51** [comment]
Are you seriously expecting me to spend money to buy these games?

**Comment by HIllya51** [comment]
No any error found for plugins. 
If you really have any question, please create issue follow template's requirement

![屏幕截图 2024-04-27 205836](https://github.com/HIllya51/LunaHook/assets/101191390/9a8e13c3-7eb1-4d31-ab55-a7da3f2c7cb7)

**Comment by HIllya51** [comment]
![屏幕截图 2024-04-27 210038](https://github.com/HIllya51/LunaHook/assets/101191390/eadba519-07f2-404a-b6d0-550fd8fa282d)

**Comment by HIllya51** [comment]
I have no interest in spending a lot of effort to find these unpopular game resources, or even spending money to buy these games myself. If you want the game to be supported, please send it to me directly through the network disk.

**Comment by churroloca** [comment]
Oh no, no, that was not my intentions at all. I cannot apologise enough,
for that misunderstanding.

I thought you were wanting the source of where I got the game. To see if it
was an error caused by where it was downloaded.

Again, that's not my intentions at all. I'm sorry, had I known how my
ticket would've come across - I would've worded it differently.

**Comment by HIllya51** [comment]
ok, create a new issue follow template please.
