### ISSUE TITLE
DRAGON QUEST® XI S: Echoes of an Elusive Age [DEMO] | and LIVE A LIVE Demo version...

### ISSUE THREAD

**Issue by q8fft2** [HIllya51/LunaHook#26]
### vndb link/id

https://store.steampowered.com/app/1295510/DRAGON_QUEST_XI_S_Echoes_of_an_Elusive_Age__Definitive_Edition/

### Game resource 游戏资源

Cannot find hook DRAGON QUEST® XI S: Echoes of an Elusive Age Demo Steam Version. Is this possible to support?

And LIVE A LIVE Demo version
https://store.steampowered.com/app/2014380/LIVE_A_LIVE/

**Comment by HIllya51** [comment]
I don't use steam.
![屏幕截图 2024-04-28 115711](https://github.com/HIllya51/LunaHook/assets/101191390/9b3994e4-ba5e-4aa8-ad2d-03e48bd30c35)
