### ISSUE TITLE
Text in dialogue box is split into separate lines

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaHook#27]
### Version 程序版本

3.1.4

### Related screenshot (optional) 相关截图（可选）

![Screenshot 2024-04-27 180139](https://github.com/HIllya51/LunaHook/assets/103087027/2d9f1591-cc75-4393-afad-9648bd5300a2)
![Screenshot 2024-04-27 180234](https://github.com/HIllya51/LunaHook/assets/103087027/e4e0149a-e1f6-48f3-9581-c8621808d537)

### Reproduction steps 复现步骤

This has been happening for awhile with the same [game](https://vndb.org/v10294) I mentioned in a LunaTranslator issue . I wanted to wait a bit after what happened last time after I didn't upload the photos correctly.

It appears that with this game, and possibly other Cyclet games, that when text appears in the dialogue box that is more than one line is split into two or three separate lines in LunaHook.

**Comment by HIllya51** [comment]
Increase the flushdelay and then use plugin in LunaHook or use text process method in Lunatranslator to filter the line separators.
<img width="329" alt="屏幕截图 2024-05-03 122346" src="https://github.com/HIllya51/LunaHook/assets/101191390/65d155c9-fead-41a7-a321-42a054ea9cb7">

**Comment by Vincent-Dawn** [comment]
I increased the flush delay to 300 and later to 400 and that seemed to work, also which plugin do I use?

I think it might be thread linker, I added it to the plug in menu, but I don't know how to use it.

**Comment by HIllya51** [comment]
Try youself, I don't use plugins.
