### ISSUE TITLE
Fix/Update Hook codes for Shin Koihime † Musou -Kakumei- Son Go no Ketsumyaku (and other games using Catsystem 3 new engine like this game)

### ISSUE THREAD

**Issue by tbhoang12** [HIllya51/LunaHook#28]
### vndb link/id

https://vndb.org/v20591#main

### Game resource 游戏资源

Download links Shin Koihime † Musou -Kakumei- Son Go no Ketsumyaku
=============================================
Torrent (in my country this gave me higher speed - don't know what it's like in China, maybe you have to use VPN )
https://sukebei.nyaa.si/view/3090816
Terabox (password: ryuugames.com)
https://www.terabox.com/sharing/link?surl=KIuQPelEb-e2-STcpyOrrg&path=%2Fr71355

**Comment by HIllya51** [comment]
ok

**Comment by HIllya51** [comment]
There's obviously no problem, why are you wasting my time?

![屏幕截图 2024-05-05 151409](https://github.com/HIllya51/LunaHook/assets/101191390/f0f5dbfb-a7e7-4b5b-84f5-d3127b626cef)
