### ISSUE TITLE
Ma Furu Yoru no Rin

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaHook#29]
### vndb link/id

https://vndb.org/v12297

### Game resource 游戏资源

Here is the link of the game 
https://drive.google.com/file/d/1JZwePzFg9n4F_DZ45QtelybMmB1jU8LB/view
when i inject luna translator on this game . No hook appear

**Comment by HIllya51** [comment]
re download the LunaTranslator and hook "CefSharp.BrowserSubprocess.exe"
![屏幕截图 2024-05-07 004843](https://github.com/HIllya51/LunaHook/assets/101191390/66371baa-6163-48a8-ba7b-68fe60667b98)
![屏幕截图 2024-05-07 004854](https://github.com/HIllya51/LunaHook/assets/101191390/b8ed14ba-a9c8-4479-9822-a43eb08e0a6b)
