### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaHook#3]
![1](https://github.com/HIllya51/LunaHook/assets/61865659/4ce9c04e-f095-446c-88f8-efbfd64193bb)
发现一个bug，就是这个显示文本的面板，到最大行数以后就不会更新了

**Comment by HIllya51** [comment]
嗯，issues/2提到这个问题了，这几天我找个时间会处理一下。

**Comment by HIllya51** [comment]
已修
