### ISSUE TITLE
hook文本不全

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#30]
### vndb link/id

v10335

### Game resource 游戏资源

https://zi0.cc/d/%60%E3%80%90%E5%90%88%E9%9B%86%E7%B3%BB%E5%88%97%E3%80%91/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86-5/2003%E5%B9%B412%E6%9C%88/%E4%BC%9A%E7%A4%BE%E5%90%88%E9%9B%86/%5B031219%5D%5Bmirage%5D%20%E3%81%9D%E3%81%93%E3%81%AB%E6%B5%B7%E3%81%8C%E3%81%82%E3%81%A3%E3%81%A6%20(DVD1%E6%9E%9A%20iso%2Bmds%20rr3').rar?sign=qCkefMiGEDw7qrWY7YzrV9G5GTMYZapsr2d-6ZTZPf4=:0

**Comment by qscasdasd** [comment]
![2](https://github.com/HIllya51/LunaHook/assets/167575533/4a493f96-1b36-44fa-b9e0-b4740b0d5fcf)

**Comment by HIllya51** [comment]
已支持

**Comment by qscasdasd** [comment]
> 已支持

如何配合翻译器使用啊，用LUNAHOOK设置里的复制到剪切板使用吗？

**Comment by HIllya51** [comment]
重新下载翻译器，已经内置。或者下载这个这的ReleaseEnglish，把dll拷贝到files/plugins/LunaHook
