### ISSUE TITLE
如何使用LunaHostCLI64.exe 

### ISSUE THREAD

**Issue by zzxdt** [HIllya51/LunaHook#31]
### Question 问题

我想借助LunaHostCLI64.exe开源一个npm包,但是我不知道它的使用方法

**Comment by HIllya51** [comment]
你可以直接看代码，解释起来比较麻烦，也不推荐使用。
https://github.com/HIllya51/LunaHook/blob/main/LunaHost/LunaHostCLI.cpp

你更应该使用ffi调用LunaHost32.dll/LunaHost64.dll，而不是使用控制台读io

**Comment by zzxdt** [comment]
> 你可以直接看代码，解释起来比较麻烦，也不推荐使用。 https://github.com/HIllya51/LunaHook/blob/main/LunaHost/LunaHostCLI.cpp
> 
> 你更应该使用ffi调用LunaHost32.dll/LunaHost64.dll，而不是使用控制台读io
嗯，我尝试调用cli.exe对于 向那种单进程的游戏,是完全可以调用的,但是对于像：贽之匣庭一个游戏对于双进程,虽然会有正确的文本出现，但更多的是 无限循环的:VRAM: 0bytes

**Comment by HIllya51** [comment]
这游戏就是会提到这个文本啊，你用cli根本处理不了的。
