### ISSUE TITLE
The Genesis Order

### ISSUE THREAD

**Issue by 668668acg** [HIllya51/LunaHook#32]
### Game resource 游戏资源

**Comment by HIllya51** [comment]
这根本不是分享链接。

**Comment by 668668acg** [comment]
https://mega.nz/file/bE0gmC5B#op6r8MWqgnj3gqQAqedwLdSaN4JpriWQcidBx53kSRI
这个是吗，实在抱歉，第一次用mega分享

**Comment by HIllya51** [comment]
服了你了，这不是有吗？

![屏幕截图 2024-05-11 121749](https://github.com/HIllya51/LunaHook/assets/101191390/700d2beb-f5e8-4536-a4e8-5ef78dc109b0)

**Comment by 668668acg** [comment]
大佬，请结束这个播片，在后面流程的对话框看看效果，实在麻烦你了，感谢

**Comment by HIllya51** [comment]
已经删了，没兴趣再下一遍了。显然第一行就是你说的不全的，但第二行就是全的，你文本处理一下就行了。

**Comment by 668668acg** [comment]
大佬，在后面的文本框对话中真没有，恳请你再帮忙看看，我已经赞助您了
![屏幕截图 2024-05-11 122928](https://github.com/HIllya51/LunaHook/assets/169470320/53ec59c5-b7b5-46f1-9719-38ed243bb5e7)

**Comment by HIllya51** [comment]
你这第一行是什么，点开看一下啊

**Comment by HIllya51** [comment]
我和你这只是这两行顺序不一样而已

**Comment by 668668acg** [comment]
![屏幕截图 2024-05-11 123828](https://github.com/HIllya51/LunaHook/assets/169470320/e10dec26-0a85-4b84-87be-d49e37f00730)
没有任何文本内容

**Comment by HIllya51** [comment]
行吧。那我再下一下

**Comment by HIllya51** [comment]
可以了，等下release
