### ISSUE TITLE
悪魔と夜と異世界と无法HOOK到文本

### ISSUE THREAD

**Issue by kunger97** [HIllya51/LunaHook#33]
### vndb link/id

r94776

### Game resource 游戏资源

https://drive.google.com/file/d/1JVvSpKOQZl5N4TthuiNsVDBR33fJw6If/view?usp=sharing

游戏程序在data目录下

### screenshot 截图

![QQ截图20240511201758](https://github.com/HIllya51/LunaHook/assets/1808555/68c2f869-a743-459c-8d51-1dbedfeabb8e)

这个破解版本似乎不需要转区，但是无论是否使用LE转区，都Hook不到正确的文本

**Comment by HIllya51** [comment]
ready https://github.com/HIllya51/LunaHook/commit/dfea2b93ce75265e08aee602b6c03e2991e18f89
