### ISSUE TITLE
リフレインブルー【Windows10対応】

### ISSUE THREAD

**Issue by sakura4214** [HIllya51/LunaHook#34]
### vndb link/id

https://vndb.org/r60807

### Game resource 游戏资源

https://drive.google.com/file/d/1sdNN5snptSQxvcwy5H1KJ8y4gGa2dHvl/view?usp=sharing

### screenshot 截图

![image](https://github.com/HIllya51/LunaHook/assets/113588801/83300993-6559-4898-afe8-503fe815131b)
不知道是不是DMM的破解问题

**Comment by HIllya51** [comment]
搞了一天没搞定，擦

**Comment by qscasdasd** [comment]
> 搞了一天没搞定，擦



> ### vndb link/id
> https://vndb.org/r60807
> 
> ### Game resource 游戏资源
> https://drive.google.com/file/d/1sdNN5snptSQxvcwy5H1KJ8y4gGa2dHvl/view?usp=sharing
> 
> ### screenshot 截图
> ![image](https://private-user-images.githubusercontent.com/113588801/329822123-83300993-6559-4898-afe8-503fe815131b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjQyMzAsIm5iZiI6MTcxNTYyMzkzMCwicGF0aCI6Ii8xMTM1ODg4MDEvMzI5ODIyMTIzLTgzMzAwOTkzLTY1NTktNDg5OC1hZmU4LTUwM2ZlODE1MTMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxODEyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmZkMzc1MzMzOGZhNGYzYjNiNWM3MDJkYzEwMzdhNjdmN2U0NmVlYjE5N2E2ZjRiYzdmYTgwMDEwN2ZhOTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7hNVuhR7uTNXe8S5CwekU3XwAtWPS2olygA1uOv6P60) 不知道是不是DMM的破解问题

这作有特殊码，插入就行了

**Comment by qscasdasd** [comment]
> ### vndb link/id
> https://vndb.org/r60807
> 
> ### Game resource 游戏资源
> https://drive.google.com/file/d/1sdNN5snptSQxvcwy5H1KJ8y4gGa2dHvl/view?usp=sharing
> 
> ### screenshot 截图
> ![image](https://private-user-images.githubusercontent.com/113588801/329822123-83300993-6559-4898-afe8-503fe815131b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY1OTcsIm5iZiI6MTcxNTYyNjI5NywicGF0aCI6Ii8xMTM1ODg4MDEvMzI5ODIyMTIzLTgzMzAwOTkzLTY1NTktNDg5OC1hZmU4LTUwM2ZlODE1MTMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxODUxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGMzOTAxNDU3NjFlZTc3M2I4MzQ0MTUxOGYxM2E2OTA0ZGY2ZDg0NzRkMTBjZTZkYzgyZWIxNWFiNGI1NDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5z71IxiyKkAi11Y4Z8OwDeuahEmrxtpla7o6aMgTr9k) 不知道是不是DMM的破解问题



> 搞了一天没搞定，擦

插入特殊码就行/HAN-18*-4@42E12:AI5WIN.exe
![2](https://github.com/HIllya51/LunaHook/assets/167575533/45e82f34-f8e9-4433-b407-2a6f9721383d)

**Comment by HIllya51** [comment]
> > ### vndb link/id
> > https://vndb.org/r60807
> > ### Game resource 游戏资源
> > https://drive.google.com/file/d/1sdNN5snptSQxvcwy5H1KJ8y4gGa2dHvl/view?usp=sharing
> > ### screenshot 截图
> > ![image](https://private-user-images.githubusercontent.com/113588801/329822123-83300993-6559-4898-afe8-503fe815131b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY1OTcsIm5iZiI6MTcxNTYyNjI5NywicGF0aCI6Ii8xMTM1ODg4MDEvMzI5ODIyMTIzLTgzMzAwOTkzLTY1NTktNDg5OC1hZmU4LTUwM2ZlODE1MTMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxODUxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGMzOTAxNDU3NjFlZTc3M2I4MzQ0MTUxOGYxM2E2OTA0ZGY2ZDg0NzRkMTBjZTZkYzgyZWIxNWFiNGI1NDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5z71IxiyKkAi11Y4Z8OwDeuahEmrxtpla7o6aMgTr9k) 不知道是不是DMM的破解问题
> 
> > 搞了一天没搞定，擦
> 
> 插入特殊码就行/HAN-18*-4@42E12:AI5WIN.exe ![2](https://private-user-images.githubusercontent.com/167575533/330172122-45e82f34-f8e9-4433-b407-2a6f9721383d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDUyNjMsIm5iZiI6MTcxNTY0NDk2MywicGF0aCI6Ii8xNjc1NzU1MzMvMzMwMTcyMTIyLTQ1ZTgyZjM0LWY4ZTktNDQzMy1iNDA3LTJhNmY5NzIxMzgzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMDAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWM2MWI2NjU1ZDA0MWEyODQ1NGIyOTU3ZTFlODg3YWQyYTgzM2ZhNjY0ZmUzYTE3MGIzMmMyZWM3MTNkMWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Glr8xaokMRdJgg1NYrjtGUJr-vCoLIEjhx_r_RAdXXc)



> > ### vndb link/id
> > https://vndb.org/r60807
> > ### Game resource 游戏资源
> > https://drive.google.com/file/d/1sdNN5snptSQxvcwy5H1KJ8y4gGa2dHvl/view?usp=sharing
> > ### screenshot 截图
> > ![image](https://private-user-images.githubusercontent.com/113588801/329822123-83300993-6559-4898-afe8-503fe815131b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY1OTcsIm5iZiI6MTcxNTYyNjI5NywicGF0aCI6Ii8xMTM1ODg4MDEvMzI5ODIyMTIzLTgzMzAwOTkzLTY1NTktNDg5OC1hZmU4LTUwM2ZlODE1MTMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxODUxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGMzOTAxNDU3NjFlZTc3M2I4MzQ0MTUxOGYxM2E2OTA0ZGY2ZDg0NzRkMTBjZTZkYzgyZWIxNWFiNGI1NDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5z71IxiyKkAi11Y4Z8OwDeuahEmrxtpla7o6aMgTr9k) 不知道是不是DMM的破解问题
> 
> > 搞了一天没搞定，擦
> 
> 插入特殊码就行/HAN-18*-4@42E12:AI5WIN.exe ![2](https://private-user-images.githubusercontent.com/167575533/330172122-45e82f34-f8e9-4433-b407-2a6f9721383d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDUyNjMsIm5iZiI6MTcxNTY0NDk2MywicGF0aCI6Ii8xNjc1NzU1MzMvMzMwMTcyMTIyLTQ1ZTgyZjM0LWY4ZTktNDQzMy1iNDA3LTJhNmY5NzIxMzgzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMDAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWM2MWI2NjU1ZDA0MWEyODQ1NGIyOTU3ZTFlODg3YWQyYTgzM2ZhNjY0ZmUzYTE3MGIzMmMyZWM3MTNkMWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Glr8xaokMRdJgg1NYrjtGUJr-vCoLIEjhx_r_RAdXXc)

牛b，从哪找到的
