### ISSUE TITLE
HOOK文本缺失

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#37]
### vndb link/id

[v1538](https://vndb.org/v1538)

### Game resource 游戏资源

https://zi0.cc/d/%60%E3%80%90%E5%90%88%E9%9B%86%E7%B3%BB%E5%88%97%E3%80%91/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86-4/2006%E5%B9%B48%E6%9C%88/%E4%BC%9A%E7%A4%BE%E5%90%88%E9%9B%86/%5B060825%5D%5BRUNE%5D%20%E4%BB%8A%E5%A4%9C%E3%81%AE%E3%82%AA%E3%82%AB%E3%82%BA%E3%81%AF%E3%83%AC%E3%83%B3%E3%82%B8de%E3%81%BE%E3%82%8A%E3%81%AD%20(mdf%2Bmds).rar?sign=DNZ0JQStvKIgxUDmno9zlEMhmnt4yuMYpJ9e_9KZg7A=:0

### screenshot 截图

![1](https://github.com/HIllya51/LunaHook/assets/167575533/409b4788-9cbb-4cd4-8e20-7a70025419c9)
不用特殊码根本HOOK不到文本，使用后（/HA8*0@46AD80 or /HAN-20@46D815）原文里有注音的汉字HOOK不到

**Comment by qscasdasd** [comment]
修正补丁与存档（有注音汉字的）：https://mega.nz/file/AbUxXQpY#D--ztMpPR-30w-7IrrhCR09BwCdg7ipFyQgNlKsaJiU

**Comment by HIllya51** [comment]
这作怎么运行，必须xp吗？

**Comment by HIllya51** [comment]
运行起来了。这作有内置hook的啊？你版本太古老了吧。
![屏幕截图 2024-05-14 090055](https://github.com/HIllya51/LunaHook/assets/101191390/3c56c7bd-059d-4424-95aa-bf2d2f68e8c9)

**Comment by HIllya51** [comment]
刚看到内置的会把注音也合到一起了

用这个特殊码可以分开他们：HA4:8*0@9B8D0:Marine.exe
![屏幕截图 2024-05-14 091515](https://github.com/HIllya51/LunaHook/assets/101191390/e7dcc776-d55b-4327-9d34-6e5c2aa6e9d0)

**Comment by HIllya51** [comment]
或者HA4:-14*0@9B8D0:Marine.exe也许，上面那个分的有点太多了
