### ISSUE TITLE
关于线程问题

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaHook#39]
![image](https://github.com/HIllya51/LunaHook/assets/61865659/4ae29a19-ae09-4f1d-9b39-1e5a66ecc465)
我记得早期版本，每个线程前面都会有个一个代号，然后使用Thread Linker.xdll 插件可以进行串联，现在版本没有了，有什么办法吗

**Comment by k2250761** [comment]
PS:因为有些线程带人名，所以想串联到一起，方便翻译

**Comment by HIllya51** [comment]
使用 [LunaTranslator](https://github.com/HIllya51/LunaTranslator)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/12ba523eddfd3ef90ef934462b5d44d1bf19b0ca
