### ISSUE TITLE
Monster Park ~Bakemono ni Miirareshi Hime

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaHook#41]
### vndb link/id

https://vndb.org/v3002

### Game resource 游戏资源

https://8fl2fw-my.sharepoint.com/personal/misakichan_digitalshop_biz_id/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmisakichan_digitalshop_biz_id%2FDocuments%2Fv3002%2F%5BRyuugames%5D%20RY-v3002%2Erar&parent=%2Fpersonal%2Fmisakichan_digitalshop_biz_id%2FDocuments%2Fv3002&ga=1

### screenshot 截图

![Capture](https://github.com/HIllya51/LunaHook/assets/167679284/484811cc-7cc6-4896-9785-6813b1bdd6d0)
It seem the hook in beginning is correct but the more i play the more the incorrect translation from the hook
plus this game have annoying cursor that keep the language overwritten from the hook . idk how to explain but if you play it 
you know what i mean

**Comment by HIllya51** [comment]
The link you gave me is not a valid link at all.

**Comment by Machinamochi** [comment]
do this link works ?
https://mega.nz/file/YEgTCCJJ#20J54g5wW6HnXFOuDY937GwcaC_1YVImu1fRmOBoP08

**Comment by HIllya51** [comment]
wait for CI https://github.com/HIllya51/LunaHook/commit/cdc207844fe577671a2d8ffba00f85e5f69a41c5

**Comment by HIllya51** [comment]
supported already.
