### ISSUE TITLE
hook文本缺失

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#43]
### vndb link/id

[v4025](https://vndb.org/v4025)

### Game resource 游戏资源

https://zi0.cc/d/%60%E3%80%90%E5%90%88%E9%9B%86%E7%B3%BB%E5%88%97%E3%80%91/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86-5/2003%E5%B9%B46%E6%9C%88/2003%E5%B9%B46%E6%9C%88/%5B030627%5D%5BQ-X%5D%20%E3%81%93%E3%81%93%E3%82%8D%E3%83%8A%E3%83%93%20(bin%2Bcue).rar?sign=XEpSEmrI_DH2LjR2GIeljwB1NiaYVfG15TaGvv0SrwI=:0

### screenshot 截图

![QQ截图20240525213935](https://github.com/HIllya51/LunaHook/assets/167575533/2d812d16-6603-472b-9920-cfea4c11dfc0)
win10能玩，https://2dfan.com/downloads/13978   我用的第二种方法

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/ab8f670f4de48eec8eb03c64c63dea9ca6f58bdc
