### ISSUE TITLE
好像还有问题

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#44]
https://github.com/HIllya51/LunaHook/commit/ab8f670f4de48eec8eb03c64c63dea9ca6f58bdc

_Originally posted by @HIllya51 in https://github.com/HIllya51/LunaHook/issues/43#issuecomment-2131311838_

**Comment by HIllya51** [comment]
？我会算命吗？

**Comment by qscasdasd** [comment]
> ？我会算命吗？
新加的HOOK文本是全能HOOK到了，但前面的文字符号之类的会跑到后面
![4](https://github.com/HIllya51/LunaHook/assets/167575533/6a9c9e41-49f2-457d-b02e-bd4665d0266f)

![2](https://github.com/HIllya51/LunaHook/assets/167575533/4735754e-36d6-4bf9-a765-41ab3b67178a)

**Comment by qscasdasd** [comment]
> 1、我游戏都已经删了，重新发给我 2、给我有问题的存档点，不然我怎么找问题

1、上次的issue里有https://github.com/HIllya51/LunaHook/issues/43#issuecomment-2131311838/
2、点新游戏进去第二句就是（有时候第一句就有问题了）
![2](https://github.com/HIllya51/LunaHook/assets/167575533/3e2b377f-dc50-4fc3-8acf-a2c2cb2943ba)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/58d90aef00ae307dd68ab4f2e6f34e94aef46bc9
