### ISSUE TITLE
hoshizora no memoria line break

### ISSUE THREAD

**Issue by NONAMEHP** [HIllya51/LunaHook#45]
### vndb link/id

v1474

### Game resource 游戏资源

Hello, I want to translate this game from English to Vietnamese, but it keeps having "~" in every line break, making the translation inaccurate.

### screenshot 截图

![Screenshot 2024-05-29 160757](https://github.com/HIllya51/LunaHook/assets/170980722/04c41f27-5616-4fb3-ab66-e5fa10ae96c4)

**Comment by HIllya51** [comment]
<img width="933" alt="屏幕截图 2024-05-29 182613" src="https://github.com/HIllya51/LunaHook/assets/101191390/f2d4806b-8f9c-4d2a-9ab5-bfb28a69cb2b">

**Comment by NONAMEHP** [comment]
Thank you I fixed it
