### ISSUE TITLE
No Correct hook appear on this game  Amairo * Islenauts

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaHook#46]
### vndb link/id

https://vndb.org/v12167

### Game resource 游戏资源

here is the link game 
https://mega.nz/folder/FqhXhSbb#T3VtpJZ4UyxLZYcJzWi2ig
Or
https://luisastralmunsi-my.sharepoint.com/personal/zayhan_luisastralmunsi_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fzayhan%5Fluisastralmunsi%5Fonmicrosoft%5Fcom%2FDocuments%2Fv12167&ga=1

### screenshot 截图

![Capture](https://github.com/HIllya51/LunaHook/assets/167679284/4255e6ec-834f-46d4-9c59-64c9c6f8b695)

**Comment by HIllya51** [comment]
nothing wrong. and it seems you are using a very old version of app...
![屏幕截图 2024-05-30 083806](https://github.com/HIllya51/LunaHook/assets/101191390/726b5cc2-d54d-46c2-8c94-975990def7db)
