### ISSUE TITLE
Sakura Tale Doesnt have any correct Hook

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaHook#49]
### vndb link/id

https://vndb.org/v1380

### Game resource 游戏资源

Here is the link
https://www.terabox.com/sharing/link?surl=603Ko0gjhsS8Eb-reeoHYA

### screenshot 截图

![Capture](https://github.com/HIllya51/LunaHook/assets/167679284/7c105c0d-89f2-4dcd-bab3-9b5d9461dd46)

**Comment by HIllya51** [comment]
HB8@59AA90

**Comment by Machinamochi** [comment]
thz it works
