### ISSUE TITLE
其他引擎提取文本

### ISSUE THREAD

**Issue by Oplay66** [HIllya51/LunaHook#5]
Lunahook 是可以支持agent 的steam 3a游戏的script？
Ue引擎是否可以加入？
Telltale games 游戏luna hook是否可以支持？

**Comment by HIllya51** [comment]
这个项目只关注视觉小说和部分RPG小黄油，我对3A不感兴趣，所以没有支持UE引擎的计划。
而Unity引擎，由于存在大量视觉小说使用Unity制作，所以已经具备对其的较为完善的支持，例如对于agent中的大部分PC_Steam_Unity_的脚本，由于LunaHook对C#的system.string底层字符串进行了hook，所以对Unity引擎的游戏具有通用性的支持。agent估计是因为没有办法选择Hook线程才只好对每个游戏都专门写的唯一性Hook而非Hook底层的string函数。
我不了解什么是Telltale games，如果它不是和视觉小说相关，那么也不会得到支持。
