### ISSUE TITLE
Issue with text filtering

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaHook#50]
### vndb link/id

https://vndb.org/v195

### Game resource 游戏资源

https://mega.nz/file/8e1UHYLC#yp-iPGVhUHowjIC_v73UMDpVZmERYMmMzJvfkqljqjY
pass : ryuugames.com

### screenshot 截图

The program does a poor job of filtering text in the English version of the game, even with different text filtering settings.
![image](https://github.com/HIllya51/LunaHook/assets/171213503/f3989a06-4c89-4379-80e0-f58e17cb890a)
![image](https://github.com/HIllya51/LunaHook/assets/171213503/b9e2c811-2e67-490e-9883-5b555defab4c)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/releases/download/v3.3.0/Release_English.zip

update the LunaHook32.dll
