### ISSUE TITLE
text hook

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaHook#52]
### vndb link/id

https://vndb.org/v5635

### Game resource 游戏资源

https://drive.google.com/drive/folders/1accDSST5x_2ENFWxccyBhui8heJypIbi
Pass: ryuugames.com
*if you want to hook this VN to Textractor or VNR, change the default font in the game settings to anything other than default, MS Gothic for example

### screenshot 截图

![image](https://github.com/HIllya51/LunaHook/assets/171213503/4bd71641-ca12-4ad9-b9fb-fb6e3266798d)

**Comment by HIllya51** [comment]
<img width="751" alt="屏幕截图 2024-06-05 142659" src="https://github.com/HIllya51/LunaHook/assets/101191390/1cfd4608-3e2b-4f13-8247-19d0d7bf5241">

**Comment by NekoIriyaRu** [comment]
> <img alt="屏幕截图 2024-06-05 142659" width="751" src="https://private-user-images.githubusercontent.com/101191390/336712601-1cfd4608-3e2b-4f13-8247-19d0d7bf5241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjkxODAsIm5iZiI6MTcxNzU2ODg4MCwicGF0aCI6Ii8xMDExOTEzOTAvMzM2NzEyNjAxLTFjZmQ0NjA4LTNlMmItNGYxMy04MjQ3LTE5ZDBkN2JmNTI0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNjI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGZjODNlNmNjMWMyM2U3M2E3NmZkNzE5NmQ3ODBlMjljZTM3NWJmNDAyZTc4ZDdkYmVhM2EyY2M2OTg5ZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.177YqdW-ALaS06jUbAE7NnillopteMRwXnxnwviVRDQ">

This text filter doesn't always work adequately. It can sometimes swallow necessary letters from words.

**Comment by NekoIriyaRu** [comment]
The text in this game doesn't always follow the exact format of AAAABBBBCCCC, although it can sometimes resemble it.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/50543f5b13f42d24ba0373d5f650e302e9ae854a

work now.

**Comment by NekoIriyaRu** [comment]
> [50543f5](https://github.com/HIllya51/LunaHook/commit/50543f5b13f42d24ba0373d5f650e302e9ae854a)
> 
> work now.

Thanks.
![image](https://github.com/HIllya51/LunaHook/assets/171213503/0461e34c-4ab6-4ec9-a0a7-6c9ddb80745b)
