### ISSUE TITLE
Luna translator cannot find this game even i open with Ntleas,Locale Remulator or emulator the game wont open to add the hook

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaHook#54]
### vndb link/id

https://vndb.org/v7343

### Game resource 游戏资源

https://mega.nz/folder/900UnRTL#VjBxifITeS92k9sxsRG8EQ

### screenshot 截图

![Capture](https://github.com/HIllya51/LunaHook/assets/167679284/40d0df35-c42a-4d4b-87f2-459f7c2deca6)

**Comment by NekoIriyaRu** [comment]
offtop
I'm curious, when will you all stop using Locale Emulator and switch to using a Japanese system?

**Comment by Machinamochi** [comment]
> offtop
> I'm curious, when will you all stop using Locale Emulator and switch to using a Japanese system?

Well this game itself is being forced to use japanese system I can open the game with that but Luna cannot inject so yeah pretty rare case for this game

**Comment by HIllya51** [comment]
run LunaTranslator_admin.exe

**Comment by NekoIriyaRu** [comment]
> > offtop
> > I'm curious, when will you all stop using Locale Emulator and switch to using a Japanese system?
> 
> Well this game itself is being forced to use japanese system I can open the game with that but Luna cannot inject so yeah pretty rare case for this game
offtop
I use the default Japanese system and I've never had any problems with games.

![1](https://github.com/HIllya51/LunaHook/assets/171213503/7e0f307c-6fe6-4ba0-b93d-d1a9f9c37b36)
