### ISSUE TITLE
gemini exception error (Hoshizora no Memoria -Wish Upon a Shooting Star)

### ISSUE THREAD

**Issue by NONAMEHP** [HIllya51/LunaHook#55]
### vndb link/id

https://vndb.org/v1474

### Game resource 游戏资源

Hoshizora no Memoria -Wish Upon a Shooting Star

### screenshot 截图

![Screenshot 2024-06-07 215958](https://github.com/HIllya51/LunaHook/assets/170980722/7e7c8a0f-c4d6-466d-aaca-5d15298de4d3)
I used to get Gemini exception errors occasionally, but they were not significant. It would only happen maybe once every 50 translations or so. However, recently I've been getting Gemini exception errors after only 3 or 4 translations.

Could you please help me find the cause of this error and fix it?

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/pull/801
ask him, i don't use gemini.
