### ISSUE TITLE
text hook #2

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaHook#56]
### vndb link/id

https://vndb.org/v1545

### Game resource 游戏资源

Games built on the Shiina Rio engine have a text issue. While the text often follows an AAAABBBBCCCC pattern, it's not always consistent. This means that a filter designed to handle AAAABBBBCCCC text can accidentally remove necessary letters from words. As a result, translations processed through this filter can become nonsensical. Here's an example of a game using the Shiina Rio engine: https://mega.nz/file/2mwlmAgS#Vu786qUVxEZ8RBx5g56B-6I6JCip5pnxWnsYM-dUF_E 
**Pass: ryuugames.com**

### screenshot 截图

![image](https://github.com/HIllya51/LunaHook/assets/171213503/9a7ad718-8bf7-42e7-a89d-d7a12830e46b)

**Comment by HIllya51** [comment]
Show me cases where text cannot be filtered

**Comment by HIllya51** [comment]
actually, it's ABCDABCDABCD pattern, not AAAABBBBCCCC pattern, I think maybe you select the wrong pattern.

**Comment by NekoIriyaRu** [comment]
> actually, it's ABCDABCDABCD pattern, not AAAABBBBCCCC pattern, I think maybe you select the wrong pattern.

Here's an example of text filtering using the ABCDABCDABCD pattern on another game. I doubt the text was filtered correctly, as the resulting translation is nonsensical. This screenshot was taken from within the game itself: https://vndb.org/v2616.
![image](https://github.com/HIllya51/LunaHook/assets/171213503/5d08becd-7ceb-41bd-b3f2-e52bbd912354)

**Comment by HIllya51** [comment]
Isn't this text completely correct? If the translation is incorrect then you should try another translation.

**Comment by NekoIriyaRu** [comment]
> Isn't this text completely correct? If the translation is incorrect then you should try another translation.

For translation, I use Google Translate API, Gemini, and DeepLX.

**Comment by HIllya51** [comment]
Screenshot with more information

**Comment by NekoIriyaRu** [comment]
> Owner

I doubt you would understand text in Russian.

**Comment by NekoIriyaRu** [comment]
![image](https://github.com/HIllya51/LunaHook/assets/171213503/019aae7c-b50f-4020-a15c-e3c1725605d0)

**Comment by NekoIriyaRu** [comment]
![image](https://github.com/HIllya51/LunaHook/assets/171213503/ab2d7c8f-882b-4ebd-b591-63dac2943dd3)
(chat gpt = gemini )

**Comment by NekoIriyaRu** [comment]
Due to the flawed text filtering, the approximate meaning of the text is lost in translation.

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-08 154508](https://github.com/HIllya51/LunaHook/assets/101191390/64ce4bb1-dc50-42df-a327-3f1db90fdc19)

There are texts without duplicates, why do you have to choose a duplicate text? Waste of my time, shit.

**Comment by NekoIriyaRu** [comment]
I can't find any non-duplicated text.

**Comment by NekoIriyaRu** [comment]
It only displays duplicated text.

![image](https://github.com/HIllya51/LunaHook/assets/171213503/897045b2-ae2d-486d-9a9c-89f7c8484f88)
