### ISSUE TITLE
PSP游戏HOOK支持可能？

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaHook#57]
### vndb link/id

https://vndb.org/v16386

### Game resource 游戏资源

https://mega.nz/file/hWthgZIb#dYu0SVy2xQg5Cc42zHTVZEy24ZZNAcqrfBrNuSsofhM

### screenshot 截图

![QQ截图20240609033408](https://github.com/HIllya51/LunaHook/assets/167575533/3a847524-a7e7-431b-b382-ad549b67cde6)
PPSSPP是0.9.8版本。绯月看到说支持部分模拟器了？能否像win版游戏那样把未能HOOK成功的游戏提取文本成功？

**Comment by qscasdasd** [comment]
@HIllya51 如果实现支持HOOK困难的话就关闭issue了，至少回复下让我知道啥情况吧

**Comment by HIllya51** [comment]
暂时还没搞定 搞定了会告诉你的

**Comment by qscasdasd** [comment]
> 暂时还没搞定 搞定了会告诉你的
感谢露娜佬，一直没回复以为是没看到

**Comment by 123456ds** [comment]
可以使用OCR识别吧

**Comment by HIllya51** [comment]
不搞了 搞不定
