### ISSUE TITLE
hook v21979

### ISSUE THREAD

**Issue by TildaRu** [HIllya51/LunaHook#58]
### vndb link/id

https://vndb.org/v21979

### Game resource 游戏资源

https://drive.google.com/file/d/1f4B9CZ5TVtVI-7_XPcLGygFZL_c1jlR-/view

### screenshot 截图

![bug1](https://github.com/HIllya51/LunaHook/assets/107315419/dfeffb64-2663-4a92-997a-5f9234767518)
![bug2](https://github.com/HIllya51/LunaHook/assets/107315419/1152b77e-8cac-4f72-a17d-a146c483750a)

**Comment by HIllya51** [comment]
Give me the savedata with the location of the wrong text

**Comment by TildaRu** [comment]
> Give me the savedata with the location of the wrong text

https://disk.yandex.com/d/C4ItWsKXVXO1NA

**Comment by HIllya51** [comment]
Give me the save file before this sentence, otherwise I won't be able to get this sentence at all.

**Comment by TildaRu** [comment]
> Give me the save file before this sentence, otherwise I won't be able to get this sentence at all.

https://disk.yandex.com/d/Waf43qs1e6CI_Q

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/a1478030f31bfeeead442222ac5cc30579a0ce22

![屏幕截图 2024-06-12 205526](https://github.com/HIllya51/LunaHook/assets/101191390/8381355d-25f4-45c0-8a49-e1d7c8ed2cfe)
