### ISSUE TITLE
"Send ERROR" on Windows XP

### ISSUE THREAD

**Issue by WetCrowsFeather** [HIllya51/LunaHook#59]
### Version 程序版本

3.4.0

### Related screenshot (optional) 相关截图（可选）

![2024-06-12 16_06_18-JWinXP  Running  - Oracle VM VirtualBox](https://github.com/HIllya51/LunaHook/assets/141647325/0ef2d801-e4f8-4705-aff7-c71760a98ba0)

### Reproduction steps 复现步骤

LunaHook works fine on Windows 10, but when testing the Windows XP build in a virtual machine I'm unable to hook anything, I only get a "Send ERROR" like in the pic.

**Comment by HIllya51** [comment]
give me resource

**Comment by WetCrowsFeather** [comment]
> give me resource

Sorry, what do you mean by resource

**Comment by HIllya51** [comment]
game resource。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/1bfae6284e2195595134f02c6c20c4456d70f3b7
