### ISSUE TITLE
妹幻想的HOOK问题，会卡死

### ISSUE THREAD

**Issue by fatecyx** [HIllya51/LunaHook#60]
### Game resource 游戏资源

https://drive.google.com/file/d/1iNQwmwmBAfmLF0ykBMve0xMD7xmhR0l6/view?usp=drive_link

### screenshot 截图

https://drive.google.com/file/d/10FOEj8FbCZTjd0d_YIB6SNa1G-qphWJQ/view?usp=drive_link
HOOK选择文本之后，没多久就会卡死
明明没有新文本，但是翻译这里看着像是在不停刷新一样，我选择了负载均衡的，下面几个引擎轮流变。（最短翻译字数是5）

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/1bfae6284e2195595134f02c6c20c4456d70f3b7
