### ISSUE TITLE
v3.4.0 Release_English.zip download blocked, flagged as malware by Chrome and DuckDuckGo browsers, 

### ISSUE THREAD

**Issue by roboticsbrian** [HIllya51/LunaHook#61]
### Version 程序版本

v3.4.0 

### Related screenshot (optional) 相关截图（可选）

On Chrome: 
![image](https://github.com/HIllya51/LunaHook/assets/47238439/34766cdb-cb6b-43d8-9cf5-806d170887f5)

On DuckDuckGo browser:
![image](https://github.com/HIllya51/LunaHook/assets/47238439/dc2b9d73-a80e-4ce2-ab0c-5043de15cf70)

### Reproduction steps 复现步骤

Trying to download [Release_English.zip](https://github.com/HIllya51/LunaHook/releases/download/v3.4.0/Release_English.zip) fails, as both Chrome and DuckDuckGo do some sort of malware detection and refuse to download the file.

**Comment by HIllya51** [comment]
dont use
