### ISSUE TITLE
翻译英文游戏，提取的英文文本不带空格，导致翻译效果很差，请问有无解决方法？

### ISSUE THREAD

**Issue by BlackTea007s** [HIllya51/LunaHook#63]
### Game resource 游戏资源

链接：https://pan.baidu.com/s/1ABaA_as_AJ_-u0xNWxsZWA?pwd=4x0c 
提取码：4x0c

### screenshot 截图

![Uploading 无标题.png…]()

**Comment by BlackTea007s** [comment]
![Uploading 无标题.png…]()

**Comment by HIllya51** [comment]
这明明是个日文游戏，你干嘛要打英文补丁再翻译。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/06e881ede5e4f5cb6c31374ebb73c1906079759a
