### ISSUE TITLE
Error invalid dll

### ISSUE THREAD

**Issue by TildaRu** [HIllya51/LunaHook#66]
### Version 程序版本

3.4.0

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/HIllya51/LunaHook/assets/107315419/bea4f1ca-a6e4-40a5-bb60-cd3bd202d92c)

### Reproduction steps 复现步骤

To encounter the error, you need to add any plugin.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/95fda44136c39dfe61ce558b1596794b49fe076a
