### ISSUE TITLE
request : add ru.h

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaHook#69]
request : add ru.h
[ru.h.txt](https://github.com/user-attachments/files/15928633/ru.h.txt)

**Comment by HIllya51** [comment]
pull request

**Comment by NekoIriyaRu** [comment]
pull request not work
![image](https://github.com/HIllya51/LunaHook/assets/171213503/4f60caf4-d6e4-457d-ba02-d2dbb5bd732b)
