### ISSUE TITLE
Never7 eternal edition (love2d engine)

### ISSUE THREAD

**Issue by AuroraWright** [HIllya51/LunaHook#73]
### vndb link/id

https://vndb.org/r77051

### Game resource 游戏资源

Link to the game is https://www.mediafire.com/file/nshjldhr3zzm760/n7e.love/file
It can be opened with the Love2d engine: https://love2d.org/ . Currently text hooking does not work at all.

### screenshot 截图

<img width="2056" alt="screenshot" src="https://github.com/HIllya51/LunaHook/assets/15571693/0e2ba70f-9b38-4469-81e9-fcc2146fb8d8">

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/dbee45b34308fe7914cb8eb41b449ca701aa1985
