### ISSUE TITLE
Request : Create new plugins

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaHook#76]
The first plugin allows you to use the DeepLx API.
The second plugin allows you to use the unofficial ChatGPT API.

**Comment by HIllya51** [comment]
use https://github.com/HIllya51/LunaTranslator

**Comment by NekoIriyaRu** [comment]
> use https://github.com/HIllya51/LunaTranslator

On a low-end device with a weak processor, it consumes a lot of RAM and the interface is overloaded with unnecessary information. The program also crashes when trying to find a hook.

**Comment by HIllya51** [comment]
only 20~50mb memory cost, i think it's not so much. 
anyway i'm not interested in create a new textractor plugin.

**Comment by NekoIriyaRu** [comment]
Searching for a hook causes Luna Translator to crash.
If you search for a hook in LunaHost, there is no crash in LunaHost.

https://github.com/HIllya51/LunaHook/assets/171213503/439a875d-740e-4f63-8c40-089231319f3e

**Comment by HIllya51** [comment]
run LunaTranslator_debug.exe and show me the error log.

**Comment by NekoIriyaRu** [comment]
> LunaTranslator_debug

To what folder does the debug log save?

**Comment by HIllya51** [comment]
screenshot. not file saved.

**Comment by NekoIriyaRu** [comment]
> screenshot. not file saved.

The program crashes very quickly and I can't take a screenshot.

**Comment by HIllya51** [comment]
open cmd and run with command line.

**Comment by NekoIriyaRu** [comment]
> open cmd and run with command line.

`C:\Program Files (x86)\ensemble\花と乙女に祝福を\HANAOTO.EXE
POST vn {'filters': ['search', '=', '花と乙女に祝福を'], 'fields': 'id', 'sort': 'searchrank'}
POST vn {'filters': ['id', '=', 'v1545'], 'fields': 'title,titles.title,titles.main,screenshots.url,image.url,developers.name,developers.original'}
POST character {'filters': ['vn', '=', ['id', '=', 'v1545']], 'fields': 'name,original'}
https://t.vndb.org/cv/41/27641.jpg cache/vndb/2368ffcd821d69ddf397ddc6b3d9212f.jpg
https://t.vndb.org/sf/51/2051.jpg cache/vndb/7dc65cffad2c5b8cc743ac597be9cfee.jpg
https://t.vndb.org/sf/62/2062.jpg cache/vndb/0071a2fd7eeede66a208731604a28e48.jpg
https://t.vndb.org/sf/63/2063.jpg cache/vndb/67849b58cd4b6d1555633ebe7be5b046.jpg
https://t.vndb.org/sf/64/2064.jpg cache/vndb/b74a4ceb65d910873f38c82479c516a0.jpg
https://t.vndb.org/sf/65/2065.jpg cache/vndb/66f7fa33b4d707e999719cc663306e14.jpg
https://t.vndb.org/sf/66/2066.jpg cache/vndb/805b7ca85d7f2df68014638f1d9f9036.jpg
https://t.vndb.org/sf/67/2067.jpg cache/vndb/76fb901e3253b02c1a82e736254cff04.jpg
https://t.vndb.org/sf/91/4291.jpg cache/vndb/8a1500b0254fe7e97f06179f40881195.jpg
https://t.vndb.org/sf/93/4293.jpg cache/vndb/3f3b34bf8061dc69781c2a31999d85f1.jpg
https://t.vndb.org/sf/94/4294.jpg cache/vndb/43086423279aa0a640877c5c6d681bdf.jpg
Traceback (most recent call last):
  File "C:\Users\User\Desktop\LunaTranslator\LunaTranslator\gui\selecthook.py", line 128, in searchstart
    usestruct.text = self.searchtext.text()
ValueError: string too long (49, maximum length 30)`

**Comment by HIllya51** [comment]
your input text is to long, it should be shorter than 30.

**Comment by NekoIriyaRu** [comment]
> fixed [HIllya51/LunaTranslator@13e3938#diff-9289ede3edaea95fa1cba48e0b3bff7a9db2bd171543f7f4877639e7255244c0](https://github.com/HIllya51/LunaTranslator/commit/13e39381ed6f0597975e09e3afa86d31c4e6422e#diff-9289ede3edaea95fa1cba48e0b3bff7a9db2bd171543f7f4877639e7255244c0)

![image](https://github.com/HIllya51/LunaHook/assets/171213503/9629ac2a-a566-49fc-899d-aeaa011abad0)
