### ISSUE TITLE
hook文本只能提取一半

### ISSUE THREAD

**Issue by qjq255** [HIllya51/LunaHook#77]
### vndb link/id

奈落の森の花

### Game resource 游戏资源

http://47.251.73.90/download/31/ce9f047b10180265/G-RJ218377.rar?s=jMmVkf-0qPyTGyGPpC_5ZG5Rv-rrx6wpNdYtIuGfGnXpSL-yVCKeUUEDMqpZJMQHvNClXP9cl5NMfNpZRzJ1kMQcFgbjIrWj2C9HsgBjiC4XzRWm12Rbczt_SuOS0JhO&ts=1719666671799

### screenshot 截图

1
![Uploading Image_1719666888031.png…]()

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/82e18635c0a9f0254d733510915fffc25872b6af
