### ISSUE TITLE
凌辱人妻温泉 无法提取文本

### ISSUE THREAD

**Issue by 123456ds** [HIllya51/LunaHook#78]
### vndb link/id

https://vndb.org/v7123

### Game resource 游戏资源

https://pixeldrain.com/u/DPXhf6q5
解压：1e6ca0cba5b7ff594f0aa8c4b6b8c103
游戏强制全屏，OCR也无法使用（好像没有与游戏在同一窗口）

### screenshot 截图

![](https://p.sda1.dev/18/40ecfff25f5c613f30e4625739540a8d/屏幕截图_26_.png)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/4bf962f8a1f67414bb224f3e7fd9a8af260fb228
