### ISSUE TITLE
bad hook

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaHook#79]
### vndb link/id

https://vndb.org/v37219

### Game resource 游戏资源

game - https://disk.yandex.com/d/DnG4DxmXPnankg
quick save - https://disk.yandex.com/d/OhcvCTJzxB_jYg

### screenshot 截图

good
![good](https://github.com/HIllya51/LunaHook/assets/171213503/e5accb23-72d8-404f-a2dc-bdc591947f14)
bad
![bad](https://github.com/HIllya51/LunaHook/assets/171213503/abcaebf6-1e2b-46fd-8285-f3e5218ae02f)

**Comment by NekoIriyaRu** [comment]
![image](https://github.com/HIllya51/LunaHook/assets/171213503/e3d37849-5836-4313-8f6c-c98a42338f45)

**Comment by HIllya51** [comment]
use japanese

**Comment by NekoIriyaRu** [comment]
> use japanese

japanese bad translate

**Comment by HIllya51** [comment]
HVF-24@18B840:sentokanojo.exe

**Comment by NekoIriyaRu** [comment]
> HVF-24@18B840:sentokanojo.exe

bad 
![image](https://github.com/HIllya51/LunaHook/assets/171213503/0380d6c1-c4b7-41cd-b987-e44be7def4aa)
