### ISSUE TITLE
Bug (?)

### ISSUE THREAD

**Issue by Lunameower** [HIllya51/LunaHook#8]
Hooks don't show up after having finished hook search
![image](https://github.com/HIllya51/LunaHook/assets/163428814/dd89fa92-53a3-4730-8d6d-44d22582e0ae)
They are, however, saved in the "savehooks.txt" file
[savehooks.txt](https://github.com/HIllya51/LunaHook/files/14918220/savehooks.txt)
Is there a way to access them via this text file or is it a bug?

**Comment by HIllya51** [comment]
no bug. I'm just too lazy to create this dialog. It feels meaningless and often leads to software crashes.

**Comment by HIllya51** [comment]
And I think viewing the searched hooks in the text is clear enough.

**Comment by HIllya51** [comment]
Now  the two NS games are all built-in supported.

**Comment by Lunameower** [comment]
Thanks
