### ISSUE TITLE
文本一次性显示超过一行时，只会翻译第二行文本

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaHook#81]
### vndb link/id

https://vndb.org/v6447

### Game resource 游戏资源

https://zi0.cc/d/%60%E3%80%90%E5%90%88%E9%9B%86%E7%B3%BB%E5%88%97%E3%80%91/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86-5/2000%E5%B9%B42%E6%9C%88/%E4%BC%9A%E7%A4%BE%E5%90%88%E9%9B%86%E9%83%A8%E5%88%86/%5B000210%5D%5BR.A.N.Software%5D%20Rainy%20Blue%20%EF%BD%9E6%E6%9C%88%E3%81%AE%E9%9B%A8%EF%BD%9E%20(bin%2Bcue).rar?sign=TT6POsNmudO9vMLAbLOSJ-aHlGzwzgDQX9Qsp1t3nzI=:0

### screenshot 截图

![QQ截图20240705140328](https://github.com/HIllya51/LunaHook/assets/137600501/80e21650-fd96-41ef-a861-60ba5e070fed)

**Comment by dnadash** [comment]
遇到过几部游戏都是这样的问题：v10733和v4464
文本是HOOK全了，但第一行的文字在翻译器都会被直接略过

**Comment by HIllya51** [comment]
刷新延迟

**Comment by dnadash** [comment]
> 刷新延迟

没效果，调高调低都一样

**Comment by HIllya51** [comment]
![屏幕截图 2024-07-05 154038](https://github.com/HIllya51/LunaHook/assets/101191390/5d4f4094-631f-42af-80bc-5eaba7e4cd28)

**Comment by dnadash** [comment]
> ![屏幕截图 2024-07-05 154038](https://private-user-images.githubusercontent.com/101191390/346045993-5d4f4094-631f-42af-80bc-5eaba7e4cd28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjY0MjksIm5iZiI6MTcyMDE2NjEyOSwicGF0aCI6Ii8xMDExOTEzOTAvMzQ2MDQ1OTkzLTVkNGY0MDk0LTYzMWYtNDJhZi04MGJjLTVlYWJhN2U0Y2QyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwNzU1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTFkZjBiOWQxNzEwYWQyY2I0ODA1NmFkODYwOTRiYTFkMDFkYmY5OWRmYzE2YTRiNzM4OGY3OGRiYzk0YjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VhrbqNp16Emavx471BsZfM4Bh7FNfe6zc4_8rQRHoV8)

![1](https://github.com/HIllya51/LunaHook/assets/137600501/505cf548-0295-4000-9c84-c521106b767a)

**Comment by HIllya51** [comment]
你调的多少。

**Comment by dnadash** [comment]
> 你调的多少。

我平时使用的是80。现在遇到问题，改成200,500甚至封顶都没用

**Comment by HIllya51** [comment]
HS4@1B7C0:Rainy.EXE

**Comment by dnadash** [comment]
> HS4@1B7C0:Rainy.EXE

感谢特殊码，不过我自己也弄好了。不知道是不是翻译缓存和每次更新我都是替换文件的影响，重下初始翻译器替换旧翻译器习惯的设置后，重新HOOK文本翻译就正常了
