### ISSUE TITLE
樱之诗不行，简单描述一下就是他无法获取hook，或者说获取的日语是乱的没法对上原文并且有些奇怪的符号。又或是直接空白。

### ISSUE THREAD

**Issue by chenys19** [HIllya51/LunaHook#86]
### Game resource 游戏资源

onedrive
part1:https://1drv.ms/u/c/e10d940fbe8eaedb/EXHsOperboVMnawzHgm4HuEB1YeJYoBZ8py_RpqcTYlmAQ?e=cQrNBE
part2:https://1drv.ms/u/c/e10d940fbe8eaedb/EW9rZZiqofNHn5RdOJnjNUMBA6NtBj4ujzXFF43B7m-ckQ?e=2CKaJ9
要是无法使用请联系我的qq或者qq邮箱
qq：1343159377
qq邮箱：1343159377@qq.com

### screenshot 截图

![1](https://github.com/user-attachments/assets/0284a16c-2c46-44e3-beff-538c6b6387fc)
我怕但图片不清楚我录了个视频
onedrive：https://1drv.ms/u/c/e10d940fbe8eaedb/EYr7RnxsS6NOlXMmBQadCooBm5xyqx2R7qMo-Khp586Bvg?e=S3d47p
要是无法使用请联系我的qq或者qq邮箱
qq：1343159377
qq邮箱：1343159377@qq.com

**Comment by chenys19** [comment]
虽然压缩包里有写，不过补充一下。游戏part的解压密码皆为     终点      （简体汉字无空格） 。

**Comment by HIllya51** [comment]
![屏幕截图 2024-07-14 193511](https://github.com/user-attachments/assets/33a0e0b2-81e7-4101-83c7-9bdd33ad0266)

**Comment by HIllya51** [comment]
你有点搞笑，运行一个貌似不完整的汉化补丁

**Comment by chenys19** [comment]
这样吗，不好意思麻烦你了。
