### ISSUE TITLE
 Inma Inkan ~Shokushu to Gattai Shite Omoidoori ni Yarikaesu~

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaHook#87]
### vndb link/id

https://vndb.org/v49569

### Game resource 游戏资源

Here is the game link
The hook text is correct but there is so many spam movemain.inchar on text it is hard to read on the game 
https://mega.nz/file/MTtlSKaY#iDGQfcpZ7RmnoF9tuVZFhVQz5uxVVhd1tanHYBIigFA

### screenshot 截图

![Capture](https://github.com/user-attachments/assets/c19b2aac-ea0a-449f-aa56-5638b0e1a6e1)

**Comment by HIllya51** [comment]
![屏幕截图 2024-07-15 224116](https://github.com/user-attachments/assets/b1c64f71-3533-456c-9b47-2ca64e6bceae)

Very annoying.Why don't you tell me your password every time? And why don't you update to the latest version and ask me after testing? Wasting my time.

**Comment by Machinamochi** [comment]
I am so sorry i forgot update . next time i will update latest version before texting
