### ISSUE TITLE
前面的字会跑到后面

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaHook#88]
### vndb link/id

https://vndb.org/v2380

### Game resource 游戏资源

https://zi0.cc/d/%60%E3%80%90%E5%90%88%E9%9B%86%E7%B3%BB%E5%88%97%E3%80%91/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86-5/2002%E5%B9%B42%E6%9C%88/%E4%BC%9A%E7%A4%BE%E5%90%88%E9%9B%86/%5B020222%5D%5B%E3%82%B7%E3%83%AB%E3%82%AD%E3%83%BC%E3%82%BA%5D%20flutter%20of%20birdsII%20%E5%A4%A9%E4%BD%BF%E3%81%9F%E3%81%A1%E3%81%AE%E7%BF%BC%20Disc1-3%20(ccd).rar?sign=PyCXt1COjvFIyfbWdXBX1heLX53QWBZFd770gwtRZCc=:0

### screenshot 截图

![3](https://github.com/user-attachments/assets/198b4f51-6a4f-4ae9-aae2-8a2a2041a63f)

用了搜到的特殊码才HOOK到的文本（/HA4@40A3A0 /KF），但也有点问题

**Comment by HIllya51** [comment]
👍考古学家

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/d5d882f7fc39cc93462a7247fed53dda470ed0e9
