### ISSUE TITLE
きら☆かの

### ISSUE THREAD

**Issue by Annemarie-Lohenstein** [HIllya51/LunaHook#95]
### vndb link/id

v50832

### Game resource 游戏资源

https://drive.google.com/file/d/1N4GlY1IotXFa9ZOe-D6q652i-Rya1T79/view

### screenshot 截图

![2024-07-26 173037](https://github.com/user-attachments/assets/238fde4e-0f0c-4027-b0dd-528739e107b9)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/3be82eab42e7432c1ec18f0c41af15c0fd1e4d72

**Comment by Annemarie-Lohenstein** [comment]
多謝你，問題解決了:D
