### ISSUE TITLE
沙耶の唄 Windows10対応版 ダウンロード版

### ISSUE THREAD

**Issue by bgs6** [HIllya51/LunaHook#96]
### vndb link/id

https://vndb.org/r65680

### Game resource 游戏资源

https://mega.nz/file/dy11GKxK#n2zCHi_d8RFzJmpgdgsE4Xu9T-B9xcbP5cHL2EBygHM

### screenshot 截图

![image](https://github.com/user-attachments/assets/b0092db1-cbf6-491a-9e37-00e276c01be6)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/commit/5ed44c223f57812f42a1b998516f6996c2dbeeed
