### ISSUE TITLE
Unsupported VN

### ISSUE THREAD

**Issue by LunaSama154** [HIllya51/LunaHook#97]
### vndb link/id

https://vndb.org/v2616

### Game resource 游戏资源

https://disk.yandex.com.tr/d/ZyszxeUIvGBkDQ

### screenshot 截图

![image](https://github.com/user-attachments/assets/6267db7e-c3d2-4c01-b181-0f9604fdf47f)

**Comment by HIllya51** [comment]
🙃not download able

**Comment by LunaSama154** [comment]
> 🙃not download able

![image](https://github.com/user-attachments/assets/a981817e-0780-4028-ba5b-15d307946bb1)

**Comment by HIllya51** [comment]
ok

**Comment by LunaSama154** [comment]
https://disk.yandex.com.tr/d/ZyszxeUIvGBkDQ
https://disk.yandex.com/d/ZyszxeUIvGBkDQ
https://disk.yandex.by/d//ZyszxeUIvGBkDQ
https://disk.yandex.kz/d/ZyszxeUIvGBkDQ

**Comment by LunaSama154** [comment]
> ok
You need to click on this button
![image](https://github.com/user-attachments/assets/ec3389ce-6b40-42d7-93c7-e468a3a5b1f6)

If you can't open the website itself, use a VPN (Vless/Shadowsocks).

**Comment by HIllya51** [comment]
？
![屏幕截图 2024-07-27 222237](https://github.com/user-attachments/assets/2676a314-0149-41e9-aa02-9a711d0ff116)

**Comment by LunaSama154** [comment]
> ？ ![屏幕截图 2024-07-27 222237](https://private-user-images.githubusercontent.com/101191390/352755322-2676a314-0149-41e9-aa02-9a711d0ff116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTEwMDMsIm5iZiI6MTcyMjA5MDcwMywicGF0aCI6Ii8xMDExOTEzOTAvMzUyNzU1MzIyLTI2NzZhMzE0LTAxNDktNDFlOS1hYTAyLTlhNzExZDBmZjExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QxNDMxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDk4YWE5MDBiMWVhNWRmNTg4ZWM3MDkxZDc0ZjZjNzBiNjRjMTA1NDFmNTNiNmNjZjkyNWQxZjRjOGVlNzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ORaOv0KpwneSUOISf8bcz_ijCpEaD4uWjjKucWmk4B0)

Watch my video than just closing the topic like that. - https://disk.yandex.com.tr/i/aAS5gj9y0gJ1Qg

**Comment by HIllya51** [comment]
try this:
HS8@0:gdi32.dll:GetTextExtentPoint32A
