### ISSUE TITLE
Unsupported VN #2

### ISSUE THREAD

**Issue by LunaSama154** [HIllya51/LunaHook#99]
### vndb link/id

https://vndb.org/v2616

### Game resource 游戏资源

https://disk.yandex.com.tr/d/ZyszxeUIvGBkDQ

### screenshot 截图

MY VIDEO - https://disk.yandex.com.tr/i/aAS5gj9y0gJ1Qg

**Comment by HIllya51** [comment]
HS8@0:gdi32.dll:GetTextExtentPoint32A

**Comment by LunaSama154** [comment]
Doubtful, but okay.

![image](https://github.com/user-attachments/assets/4e6bba38-6ad9-431d-800c-5df44cf57ec8)

**Comment by LunaSama154** [comment]
Thank you.

**Comment by LunaSama154** [comment]
I Tested the hook on a game that uses the same game engine.
